while IFS= read -r line; do
    php index_cache.php "&lang=tamil&q=$line" >> "./cache/tamil/$line"
    php index_cache.php "&lang=telugu&q=$line" >> "./cache/telugu/$line"
    php index_cache.php "&lang=marathi&q=$line" >> "./cache/marathi/$line"
    php index_cache.php "&lang=kannada&q=$line" >> "./cache/kannada/$line"
    php index_cache.php "&lang=filipino&q=$line" >> "./cache/filipino/$line"
    php index_cache.php "&lang=bengali&q=$line" >> "./cache/bengali/$line"
    php index_cache.php "&lang=hindi&q=$line" >> "./cache/hindi/$line"
    php index_cache.php "&lang=gujarati&q=$line" >> "./cache/gujarati/$line"
    php index_cache.php "&lang=punjabi&q=$line" >> "./cache/punjabi/$line"
    php index_cache.php "&lang=sinhala&q=$line" >> "./cache/sinhala/$line"
    php index_cache.php "&lang=swahili&q=$line" >> "./cache/swahili/$line"
    php index_cache.php "&lang=nepali&q=$line" >> "./cache/nepali/$line"
    php index_cache.php "&lang=cebuano&q=$line" >> "./cache/cebuano/$line"
    php index_cache.php "&lang=afrikaans&q=$line" >> "./cache/afrikaans/$line"
    php index_cache.php "&lang=hausa&q=$line" >> "./cache/hausa/$line"
    php index_cache.php "&lang=malay&q=$line" >> "./cache/malay/$line"
    php index_cache.php "&lang=urdu&q=$line" >> "./cache/urdu/$line"
    php index_cache.php "&lang=yoruba&q=$line" >> "./cache/yoruba/$line"
    php index_cache.php "&lang=amharic&q=$line" >> "./cache/amharic/$line"
    php index_cache.php "&lang=zulu&q=$line" >> "./cache/zulu/$line"
done < word_list.txt