mv ../index_files/afrikaans.html.gz /mnt/volume_sgp1_05/all_cache_files/afrikaans/index.html.gz
mv ../index_files/albanian.html.gz /mnt/volume_sgp1_05/all_cache_files/albanian/index.html.gz
mv ../index_files/amharic.html.gz /mnt/volume_sgp1_05/all_cache_files/amharic/index.html.gz
mv ../index_files/armenian.html.gz /mnt/volume_sgp1_05/all_cache_files/armenian/index.html.gz
mv ../index_files/azerbaijani.html.gz /mnt/volume_sgp1_05/all_cache_files/azerbaijani/index.html.gz
mv ../index_files/basque.html.gz /mnt/volume_sgp1_05/all_cache_files/basque/index.html.gz
mv ../index_files/belarusian.html.gz /mnt/volume_sgp1_05/all_cache_files/belarusian/index.html.gz
mv ../index_files/bosnian.html.gz /mnt/volume_sgp1_05/all_cache_files/bosnian/index.html.gz
mv ../index_files/bulgarian.html.gz /mnt/volume_sgp1_05/all_cache_files/bulgarian/index.html.gz
mv ../index_files/catalan.html.gz /mnt/volume_sgp1_05/all_cache_files/catalan/index.html.gz
mv ../index_files/cebuano.html.gz /mnt/volume_sgp1_05/all_cache_files/cebuano/index.html.gz
mv ../index_files/chichewa.html.gz /mnt/volume_sgp1_05/all_cache_files/chichewa/index.html.gz
mv ../index_files/chinese.html.gz /mnt/volume_sgp1_05/all_cache_files/chinese/index.html.gz
mv ../index_files/corsican.html.gz /mnt/volume_sgp1_05/all_cache_files/corsican/index.html.gz
mv ../index_files/croatian.html.gz /mnt/volume_sgp1_05/all_cache_files/croatian/index.html.gz
mv ../index_files/czech.html.gz /mnt/volume_sgp1_05/all_cache_files/czech/index.html.gz
mv ../index_files/danish.html.gz /mnt/volume_sgp1_05/all_cache_files/danish/index.html.gz
mv ../index_files/dutch.html.gz /mnt/volume_sgp1_05/all_cache_files/dutch/index.html.gz
mv ../index_files/esperanto.html.gz /mnt/volume_sgp1_05/all_cache_files/esperanto/index.html.gz
mv ../index_files/estonian.html.gz /mnt/volume_sgp1_05/all_cache_files/estonian/index.html.gz
mv ../index_files/filipino.html.gz /mnt/volume_sgp1_05/all_cache_files/filipino/index.html.gz
mv ../index_files/finnish.html.gz /mnt/volume_sgp1_05/all_cache_files/finnish/index.html.gz
mv ../index_files/french.html.gz /mnt/volume_sgp1_05/all_cache_files/french/index.html.gz
mv ../index_files/frisian.html.gz /mnt/volume_sgp1_05/all_cache_files/frisian/index.html.gz
mv ../index_files/galician.html.gz /mnt/volume_sgp1_05/all_cache_files/galician/index.html.gz
mv ../index_files/georgian.html.gz /mnt/volume_sgp1_05/all_cache_files/georgian/index.html.gz
mv ../index_files/german.html.gz /mnt/volume_sgp1_05/all_cache_files/german/index.html.gz
mv ../index_files/greek.html.gz /mnt/volume_sgp1_05/all_cache_files/greek/index.html.gz
mv ../index_files/gujarati.html.gz /mnt/volume_sgp1_05/all_cache_files/gujarati/index.html.gz
mv ../index_files/haitian.html.gz /mnt/volume_sgp1_05/all_cache_files/haitian/index.html.gz
mv ../index_files/hausa.html.gz /mnt/volume_sgp1_05/all_cache_files/hausa/index.html.gz
mv ../index_files/hawaiian.html.gz /mnt/volume_sgp1_05/all_cache_files/hawaiian/index.html.gz
mv ../index_files/hebrew.html.gz /mnt/volume_sgp1_05/all_cache_files/hebrew/index.html.gz
mv ../index_files/hmong.html.gz /mnt/volume_sgp1_05/all_cache_files/hmong/index.html.gz
mv ../index_files/hungarian.html.gz /mnt/volume_sgp1_05/all_cache_files/hungarian/index.html.gz
mv ../index_files/icelandic.html.gz /mnt/volume_sgp1_05/all_cache_files/icelandic/index.html.gz
mv ../index_files/igbo.html.gz /mnt/volume_sgp1_05/all_cache_files/igbo/index.html.gz
mv ../index_files/indonesian.html.gz /mnt/volume_sgp1_05/all_cache_files/indonesian/index.html.gz
mv ../index_files/irish.html.gz /mnt/volume_sgp1_05/all_cache_files/irish/index.html.gz
mv ../index_files/italian.html.gz /mnt/volume_sgp1_05/all_cache_files/italian/index.html.gz
mv ../index_files/japanese.html.gz /mnt/volume_sgp1_05/all_cache_files/japanese/index.html.gz
mv ../index_files/javanese.html.gz /mnt/volume_sgp1_05/all_cache_files/javanese/index.html.gz
mv ../index_files/kazakh.html.gz /mnt/volume_sgp1_05/all_cache_files/kazakh/index.html.gz
mv ../index_files/khmer.html.gz /mnt/volume_sgp1_05/all_cache_files/khmer/index.html.gz
mv ../index_files/korean.html.gz /mnt/volume_sgp1_05/all_cache_files/korean/index.html.gz
mv ../index_files/kurmanji.html.gz /mnt/volume_sgp1_05/all_cache_files/kurmanji/index.html.gz
mv ../index_files/kyrgyz.html.gz /mnt/volume_sgp1_05/all_cache_files/kyrgyz/index.html.gz
mv ../index_files/lao.html.gz /mnt/volume_sgp1_05/all_cache_files/lao/index.html.gz
mv ../index_files/latin.html.gz /mnt/volume_sgp1_05/all_cache_files/latin/index.html.gz
mv ../index_files/latvian.html.gz /mnt/volume_sgp1_05/all_cache_files/latvian/index.html.gz
mv ../index_files/lithuanian.html.gz /mnt/volume_sgp1_05/all_cache_files/lithuanian/index.html.gz
mv ../index_files/luxembourgish.html.gz /mnt/volume_sgp1_05/all_cache_files/luxembourgish/index.html.gz
mv ../index_files/macedonian.html.gz /mnt/volume_sgp1_05/all_cache_files/macedonian/index.html.gz
mv ../index_files/malagasy.html.gz /mnt/volume_sgp1_05/all_cache_files/malagasy/index.html.gz
mv ../index_files/malayalam.html.gz /mnt/volume_sgp1_05/all_cache_files/malayalam/index.html.gz
mv ../index_files/maltese.html.gz /mnt/volume_sgp1_05/all_cache_files/maltese/index.html.gz
mv ../index_files/maori.html.gz /mnt/volume_sgp1_05/all_cache_files/maori/index.html.gz
mv ../index_files/marathi.html.gz /mnt/volume_sgp1_05/all_cache_files/marathi/index.html.gz
mv ../index_files/mongolian.html.gz /mnt/volume_sgp1_05/all_cache_files/mongolian/index.html.gz
mv ../index_files/burmese.html.gz /mnt/volume_sgp1_05/all_cache_files/burmese/index.html.gz
mv ../index_files/norwegian.html.gz /mnt/volume_sgp1_05/all_cache_files/norwegian/index.html.gz
mv ../index_files/pashto.html.gz /mnt/volume_sgp1_05/all_cache_files/pashto/index.html.gz
mv ../index_files/persian.html.gz /mnt/volume_sgp1_05/all_cache_files/persian/index.html.gz
mv ../index_files/polish.html.gz /mnt/volume_sgp1_05/all_cache_files/polish/index.html.gz
mv ../index_files/portuguese.html.gz /mnt/volume_sgp1_05/all_cache_files/portuguese/index.html.gz
mv ../index_files/romanian.html.gz /mnt/volume_sgp1_05/all_cache_files/romanian/index.html.gz
mv ../index_files/russian.html.gz /mnt/volume_sgp1_05/all_cache_files/russian/index.html.gz
mv ../index_files/samoan.html.gz /mnt/volume_sgp1_05/all_cache_files/samoan/index.html.gz
mv ../index_files/serbian.html.gz /mnt/volume_sgp1_05/all_cache_files/serbian/index.html.gz
mv ../index_files/shona.html.gz /mnt/volume_sgp1_05/all_cache_files/shona/index.html.gz
mv ../index_files/sindhi.html.gz /mnt/volume_sgp1_05/all_cache_files/sindhi/index.html.gz
mv ../index_files/sinhala.html.gz /mnt/volume_sgp1_05/all_cache_files/sinhala/index.html.gz
mv ../index_files/slovak.html.gz /mnt/volume_sgp1_05/all_cache_files/slovak/index.html.gz
mv ../index_files/slovenian.html.gz /mnt/volume_sgp1_05/all_cache_files/slovenian/index.html.gz
mv ../index_files/somali.html.gz /mnt/volume_sgp1_05/all_cache_files/somali/index.html.gz
mv ../index_files/spanish.html.gz /mnt/volume_sgp1_05/all_cache_files/spanish/index.html.gz
mv ../index_files/sundanese.html.gz /mnt/volume_sgp1_05/all_cache_files/sundanese/index.html.gz
mv ../index_files/swahili.html.gz /mnt/volume_sgp1_05/all_cache_files/swahili/index.html.gz
mv ../index_files/swedish.html.gz /mnt/volume_sgp1_05/all_cache_files/swedish/index.html.gz
mv ../index_files/tajik.html.gz /mnt/volume_sgp1_05/all_cache_files/tajik/index.html.gz
mv ../index_files/turkish.html.gz /mnt/volume_sgp1_05/all_cache_files/turkish/index.html.gz
mv ../index_files/ukrainian.html.gz /mnt/volume_sgp1_05/all_cache_files/ukrainian/index.html.gz
mv ../index_files/urdu.html.gz /mnt/volume_sgp1_05/all_cache_files/urdu/index.html.gz
mv ../index_files/uzbek.html.gz /mnt/volume_sgp1_05/all_cache_files/uzbek/index.html.gz
mv ../index_files/vietnamese.html.gz /mnt/volume_sgp1_05/all_cache_files/vietnamese/index.html.gz
mv ../index_files/xhosa.html.gz /mnt/volume_sgp1_05/all_cache_files/xhosa/index.html.gz
mv ../index_files/yiddish.html.gz /mnt/volume_sgp1_05/all_cache_files/yiddish/index.html.gz
mv ../index_files/yoruba.html.gz /mnt/volume_sgp1_05/all_cache_files/yoruba/index.html.gz
mv ../index_files/zulu.html.gz /mnt/volume_sgp1_05/all_cache_files/zulu/index.html.gz
mv ../index_files/bengali.html.gz /mnt/volume_sgp1_05/all_cache_files/bengali/index.html.gz
mv ../index_files/hindi.html.gz /mnt/volume_sgp1_05/all_cache_files/hindi/index.html.gz
mv ../index_files/tamil.html.gz /mnt/volume_sgp1_05/all_cache_files/tamil/index.html.gz
mv ../index_files/telugu.html.gz /mnt/volume_sgp1_05/all_cache_files/telugu/index.html.gz
mv ../index_files/gujarati.html.gz /mnt/volume_sgp1_05/all_cache_files/gujarati/index.html.gz
mv ../index_files/marathi.html.gz /mnt/volume_sgp1_05/all_cache_files/marathi/index.html.gz
mv ../index_files/kannada.html.gz /mnt/volume_sgp1_05/all_cache_files/kannada/index.html.gz
mv ../index_files/thai.html.gz /mnt/volume_sgp1_05/all_cache_files/thai/index.html.gz
mv ../index_files/welsh.html.gz /mnt/volume_sgp1_05/all_cache_files/welsh/index.html.gz
mv ../index_files/arabic.html.gz /mnt/volume_sgp1_05/all_cache_files/arabic/index.html.gz
mv ../index_files/malay.html.gz /mnt/volume_sgp1_05/all_cache_files/malay/index.html.gz
mv ../index_files/nepali.html.gz /mnt/volume_sgp1_05/all_cache_files/nepali/index.html.gz
mv ../index_files/punjabi.html.gz /mnt/volume_sgp1_05/all_cache_files/punjabi/index.html.gz
