<?php 
include('header.php');


$sql = "select word, mean from x_".$lang." where word in ('awake','bear','bear','abide','arise','be','draw','do','fight','eat','drive','drink','dig','beat','become','bid','begin','bind','find','fly','forget','forgive','bite','blow','come','choose','break','behold','sit','sink','sing','shine','shake','see','get','go','give','grow','run','ring','hide','hang','hold','know','lie','mistake','ride','slay','speak','spin','stand','write','win','wear','wake','steal','stick','swear','swim','take','tear','sting','throw','chide','cleave','cling','spring','smite','slide','tread','swing','strive','string','shrink','lead','grind','freeze','forsake','fling','wring','wind','weave','bet','cast','cost','cut','hit','hurt','let','put','rid','set','shed','split','shut','thrust','spread','burst','abuse','abolish','avail','attract','appoint','apply','approve','accept','accompany','acquire','annoy','alter','aim','add','adapt','attack','assure','ask','ascend','agree','advise','adopt','bend','believe','behave','beg','bleed','bring','charge','cheat','compare','build','burn','buy','call','cry','deliver','debar','deal','dare','catch','cook','creep','change','complain','compose','convict','cure','decide','dedicate','hear','hate','have','hang','demand','deny','depend','destroy','gather','gaze','flee','feel','feed','determine','deviate','die','dream','divide','inform','inspire','introduce','embellish','enter','expressed','maintain','marry','make','insist','invade','invite','involve','lose','look','like','light','lie','joke','keep','kill','kneel','laugh','lend','leave','learn','lead','lay','owe','order','omit','occur','observe','open','occupy','pray','punish','play','pay','preside','prevent','negotiate','mow','move','mix','mend','meet','mean','manage','prepare','preserve','pretend','proceed','prohibit','reject','rehabilitate','refuse','refund','recover','propose','prosecute','prove','persist','realize','raise','receive','reach','read','quarrel','say','sew','seek','remind','remit','return','respond','rob','repair','reply','rescue','swell','sell','sweep','send','shoot','spoil','sleep','show','sow','stay','spend','work','wish','wait','warn','smile','smell','teach','want','walk','visit','vanish','tell','think','travel','tremble','utter','unite','twinkle','treat','bend','breed','clothe','gird','hew','lean','load','melt','rend','spell','knock','repeat','pick','join','clean','match','offer','plunge','watch','slip','chatter','shock','shook','affect','last','plan','expose','tip','need','suit','fold','decorate','disappear','plough','ban','protect','reproduce','contain','stretch','notice') limit 317";

$x_lang_query = mysqli_query($conn, $sql);

while($row = mysqli_fetch_assoc($x_lang_query)){
	$x_lang_array[$row['word']] = $row['mean'];
}

?>
<style>
.box_wrapper fieldset .fieldset_body span {float: none !important;}
.inner_details span { border-bottom: none !important; }
table {width:100% !important; border: 1px solid #ccc; padding: 5px; border-collapse: collapse;}
table, th, td { border: 1px solid #ccc;}
table td {padding: 5px;}
</style>
                <!--Specific Page Content-->
                <div class="box_wrapper">
				
					<div><a href="<?=$base_url?>english-to-<?= $lang ?>-dictionary-form-of-verbs" title="form of verbs"><img src="<?=$contentUrl?>banners/form-of-verbs.jpg" alt="form of verbs" style="width:100%" /></a></div>
<?php

echo $alladcodes['300'];

?>
				
                    <fieldset>
                        <legend>Form of Verbs</legend>
						
                        <div class="fieldset_body inner_details">


<table dir="ltr" cellspacing="5">
<thead>
<tr>
<th>Present Form</th>
<th>Meaning</th>
<th>Past Form</th>
<th>Past Participle</th>
</tr>
</thead>
<tbody>
<tr>
<td>awake</td>
<td><?=$x_lang_array['awake']?></td>
<td>awoke</td>
<td>awoken</td>
</tr>
<tr>
<td>bear</td>
<td><?=$x_lang_array['bear']?></td>
<td>bore</td>
<td>born</td>
</tr>
<tr>
<td>bear</td>
<td><?=$x_lang_array['bear']?></td>
<td>bore</td>
<td>borne</td>
</tr>
<tr>
<td>abide</td>
<td><?=$x_lang_array['abide']?></td>
<td>abode</td>
<td>abode</td>
</tr>
<tr>
<td>arise</td>
<td><?=$x_lang_array['arise']?></td>
<td>arose</td>
<td>arisen</td>
</tr>
<tr>
<td>be</td>
<td><?=$x_lang_array['be']?></td>
<td>was</td>
<td>been</td>
</tr>
<tr>
<td>draw</td>
<td><?=$x_lang_array['draw']?></td>
<td>drew</td>
<td>drawn</td>
</tr>
<tr>
<td>do</td>
<td><?=$x_lang_array['do']?></td>
<td>did</td>
<td>done</td>
</tr>
<tr>
<td>fight</td>
<td><?=$x_lang_array['fight']?></td>
<td>fought</td>
<td>fought</td>
</tr>
<tr>
<td>eat</td>
<td><?=$x_lang_array['eat']?></td>
<td>ate</td>
<td>eaten</td>
</tr>
<tr>
<td>drive</td>
<td><?=$x_lang_array['drive']?></td>
<td>drove</td>
<td>driven</td>
</tr>
<tr>
<td>drink</td>
<td><?=$x_lang_array['drink']?></td>
<td>drank</td>
<td>drunk</td>
</tr>
<tr>
<td>dig</td>
<td><?=$x_lang_array['dig']?></td>
<td>dug</td>
<td>dug</td>
</tr>
<tr>
<td>beat</td>
<td><?=$x_lang_array['beat']?></td>
<td>beat</td>
<td>beaten</td>
</tr>
<tr>
<td>become</td>
<td><?=$x_lang_array['become']?></td>
<td>became</td>
<td>become</td>
</tr>
<tr>
<td>bid</td>
<td><?=$x_lang_array['bid']?></td>
<td>bid</td>
<td>bid</td>
</tr>
<tr>
<td>begin</td>
<td><?=$x_lang_array['begin']?></td>
<td>began</td>
<td>begun</td>
</tr>
<tr>
<td>bind</td>
<td><?=$x_lang_array['bind']?></td>
<td>bound</td>
<td>bound</td>
</tr>
<tr>
<td>find</td>
<td><?=$x_lang_array['find']?></td>
<td>found</td>
<td>found</td>
</tr>
<tr>
<td>fly</td>
<td><?=$x_lang_array['fly']?></td>
<td>flew</td>
<td>flown</td>
</tr>
<tr>
<td>forget</td>
<td><?=$x_lang_array['forget']?></td>
<td>forgot</td>
<td>forgotten</td>
</tr>
<tr>
<td>forgive</td>
<td><?=$x_lang_array['forgive']?></td>
<td>forgave</td>
<td>forgiven</td>
</tr>
<tr>
<td>bite</td>
<td><?=$x_lang_array['bite']?></td>
<td>bit</td>
<td>bit, bitten</td>
</tr>
<tr>
<td>blow</td>
<td><?=$x_lang_array['blow']?></td>
<td>blew</td>
<td>blown</td>
</tr>
<tr>
<td>come</td>
<td><?=$x_lang_array['come']?></td>
<td>came</td>
<td>come</td>
</tr>
<tr>
<td>choose</td>
<td><?=$x_lang_array['choose']?></td>
<td>chose</td>
<td>chosen</td>
</tr>
<tr>
<td>break</td>
<td><?=$x_lang_array['break']?></td>
<td>broke</td>
<td>broken</td>
</tr>
<tr>
<td>behold</td>
<td><?=$x_lang_array['behold']?></td>
<td>beheld</td>
<td>beheld</td>
</tr>
<tr>
<td>sit</td>
<td><?=$x_lang_array['sit']?></td>
<td>sat</td>
<td>sat</td>
</tr>
<tr>
<td>sink</td>
<td><?=$x_lang_array['sink']?></td>
<td>sank</td>
<td>sunk</td>
</tr>
<tr>
<td>sing</td>
<td><?=$x_lang_array['sing']?></td>
<td>sang</td>
<td>sung</td>
</tr>
<tr>
<td>shine</td>
<td><?=$x_lang_array['shine']?></td>
<td>shone</td>
<td>shone</td>
</tr>
<tr>
<td>shake</td>
<td><?=$x_lang_array['shake']?></td>
<td>shook</td>
<td>shook</td>
</tr>
<tr>
<td>see</td>
<td><?=$x_lang_array['see']?></td>
<td>saw</td>
<td>seen</td>
</tr>
<tr>
<td>get</td>
<td><?=$x_lang_array['get']?></td>
<td>got</td>
<td>got,gotten</td>
</tr>
<tr>
<td>go</td>
<td><?=$x_lang_array['go']?></td>
<td>went</td>
<td>gone</td>
</tr>
<tr>
<td>give</td>
<td><?=$x_lang_array['give']?></td>
<td>gave</td>
<td>given</td>
</tr>
<tr>
<td>grow</td>
<td><?=$x_lang_array['grow']?></td>
<td>grew</td>
<td>grown</td>
</tr>
<tr>
<td>run</td>
<td><?=$x_lang_array['run']?></td>
<td>ran</td>
<td>run</td>
</tr>
<tr>
<td>ring</td>
<td><?=$x_lang_array['ring']?></td>
<td>rang</td>
<td>rung</td>
</tr>
<tr>
<td>hide</td>
<td><?=$x_lang_array['hide']?></td>
<td>hid</td>
<td>hid,hidden</td>
</tr>
<tr>
<td>hang</td>
<td><?=$x_lang_array['hang']?></td>
<td>hung</td>
<td>hung</td>
</tr>
<tr>
<td>hold</td>
<td><?=$x_lang_array['hold']?></td>
<td>held</td>
<td>held</td>
</tr>
<tr>
<td>know</td>
<td><?=$x_lang_array['know']?></td>
<td>knew</td>
<td>known</td>
</tr>
<tr>
<td>lie</td>
<td><?=$x_lang_array['lie']?></td>
<td>lay</td>
<td>lain</td>
</tr>
<tr>
<td>mistake</td>
<td><?=$x_lang_array['mistake']?></td>
<td>mistook</td>
<td>mistaken</td>
</tr>
<tr>
<td>ride</td>
<td><?=$x_lang_array['ride']?></td>
<td>rode</td>
<td>ridden</td>
</tr>
<tr>
<td>slay</td>
<td><?=$x_lang_array['slay']?></td>
<td>slew</td>
<td>slain</td>
</tr>
<tr>
<td>speak</td>
<td><?=$x_lang_array['speak']?></td>
<td>spoke</td>
<td>spoken</td>
</tr>
<tr>
<td>spin</td>
<td><?=$x_lang_array['spin']?></td>
<td>spun</td>
<td>spun</td>
</tr>
<tr>
<td>stand</td>
<td><?=$x_lang_array['stand']?></td>
<td>stood</td>
<td>stood</td>
</tr>
<tr>
<td>write</td>
<td><?=$x_lang_array['write']?></td>
<td>wrote</td>
<td>written</td>
</tr>
<tr>
<td>win</td>
<td><?=$x_lang_array['win']?></td>
<td>won</td>
<td>won</td>
</tr>
<tr>
<td>wear</td>
<td><?=$x_lang_array['wear']?></td>
<td>wore</td>
<td>worn</td>
</tr>
<tr>
<td>wake</td>
<td><?=$x_lang_array['wake']?></td>
<td>woke</td>
<td>woke</td>
</tr>
<tr>
<td>steal</td>
<td><?=$x_lang_array['steal']?></td>
<td>stole</td>
<td>stolen</td>
</tr>
<tr>
<td>stick</td>
<td><?=$x_lang_array['stick']?></td>
<td>stuck</td>
<td>stuck</td>
</tr>
<tr>
<td>swear</td>
<td><?=$x_lang_array['swear']?></td>
<td>swore</td>
<td>swore</td>
</tr>
<tr>
<td>swim</td>
<td><?=$x_lang_array['swim']?></td>
<td>swam</td>
<td>swum</td>
</tr>
<tr>
<td>take</td>
<td><?=$x_lang_array['take']?></td>
<td>took</td>
<td>taken</td>
</tr>
<tr>
<td>tear</td>
<td><?=$x_lang_array['tear']?></td>
<td>tore</td>
<td>torn</td>
</tr>
<tr>
<td>sting</td>
<td><?=$x_lang_array['sting']?></td>
<td>stung</td>
<td>stung</td>
</tr>
<tr>
<td>throw</td>
<td><?=$x_lang_array['throw']?></td>
<td>threw</td>
<td>thrown</td>
</tr>
<tr>
<td>chide</td>
<td><?=$x_lang_array['chide']?></td>
<td>chid</td>
<td>chid</td>
</tr>
<tr>
<td>cleave</td>
<td><?=$x_lang_array['cleave']?></td>
<td>clove,cleft</td>
<td>cloven,cleft</td>
</tr>
<tr>
<td>cling</td>
<td><?=$x_lang_array['cling']?></td>
<td>clung</td>
<td>clung</td>
</tr>
<tr>
<td>spring</td>
<td><?=$x_lang_array['spring']?></td>
<td>sprang</td>
<td>sprung</td>
</tr>
<tr>
<td>smite</td>
<td><?=$x_lang_array['smite']?></td>
<td>smote</td>
<td>smitten</td>
</tr>
<tr>
<td>slide</td>
<td><?=$x_lang_array['slide']?></td>
<td>slid</td>
<td>slid</td>
</tr>
<tr>
<td>tread</td>
<td><?=$x_lang_array['tread']?></td>
<td>trod</td>
<td>trodden</td>
</tr>
<tr>
<td>swing</td>
<td><?=$x_lang_array['swing']?></td>
<td>swang</td>
<td>swung</td>
</tr>
<tr>
<td>strive</td>
<td><?=$x_lang_array['strive']?></td>
<td>strove</td>
<td>striven</td>
</tr>
<tr>
<td>string</td>
<td><?=$x_lang_array['string']?></td>
<td>strung</td>
<td>strung</td>
</tr>
<tr>
<td>shrink</td>
<td><?=$x_lang_array['shrink']?></td>
<td>shrank</td>
<td>shrunk</td>
</tr>
<tr>
<td>lead</td>
<td><?=$x_lang_array['lead']?></td>
<td>led</td>
<td>led</td>
</tr>
<tr>
<td>grind</td>
<td><?=$x_lang_array['grind']?></td>
<td>ground</td>
<td>ground</td>
</tr>
<tr>
<td>freeze</td>
<td><?=$x_lang_array['freeze']?></td>
<td>froze</td>
<td>frozen</td>
</tr>
<tr>
<td>forsake</td>
<td><?=$x_lang_array['forsake']?></td>
<td>forsook</td>
<td>forsaken</td>
</tr>
<tr>
<td>fling</td>
<td><?=$x_lang_array['fling']?></td>
<td>flung</td>
<td>flung</td>
</tr>
<tr>
<td>wring</td>
<td><?=$x_lang_array['wring']?></td>
<td>wrung</td>
<td>wrung</td>
</tr>
<tr>
<td>wind</td>
<td><?=$x_lang_array['wind']?></td>
<td>wound</td>
<td>wound</td>
</tr>
<tr>
<td>weave</td>
<td><?=$x_lang_array['weave']?></td>
<td>wove</td>
<td>woven</td>
</tr>
<tr>
<td>bet</td>
<td><?=$x_lang_array['bet']?></td>
<td>bet</td>
<td>bet</td>
</tr>
<tr>
<td>cast</td>
<td><?=$x_lang_array['cast']?></td>
<td>cast</td>
<td>cast</td>
</tr>
<tr>
<td>cost</td>
<td><?=$x_lang_array['cost']?></td>
<td>cost</td>
<td>cost</td>
</tr>
<tr>
<td>cut</td>
<td><?=$x_lang_array['cut']?></td>
<td>cut</td>
<td>cut</td>
</tr>
<tr>
<td>hit</td>
<td><?=$x_lang_array['hit']?></td>
<td>hit</td>
<td>hit</td>
</tr>
<tr>
<td>hurt</td>
<td><?=$x_lang_array['hurt']?></td>
<td>hurt</td>
<td>hurt</td>
</tr>
<tr>
<td>let</td>
<td><?=$x_lang_array['let']?></td>
<td>let</td>
<td>let</td>
</tr>
<tr>
<td>put</td>
<td><?=$x_lang_array['put']?></td>
<td>put</td>
<td>put</td>
</tr>
<tr>
<td>rid</td>
<td><?=$x_lang_array['rid']?></td>
<td>rid</td>
<td>rid</td>
</tr>
<tr>
<td>set</td>
<td><?=$x_lang_array['set']?></td>
<td>set</td>
<td>set</td>
</tr>
<tr>
<td>shed</td>
<td><?=$x_lang_array['shed']?></td>
<td>shed</td>
<td>shed</td>
</tr>
<tr>
<td>split</td>
<td><?=$x_lang_array['split']?></td>
<td>split</td>
<td>split</td>
</tr>
<tr>
<td>shut</td>
<td><?=$x_lang_array['shut']?></td>
<td>shut</td>
<td>shut</td>
</tr>
<tr>
<td>thrust</td>
<td><?=$x_lang_array['thrust']?></td>
<td>thrust</td>
<td>thrust</td>
</tr>
<tr>
<td>spread</td>
<td><?=$x_lang_array['spread']?></td>
<td>spread</td>
<td>spread</td>
</tr>
<tr>
<td>burst</td>
<td><?=$x_lang_array['burst']?></td>
<td>burst</td>
<td>burst</td>
</tr>
<tr>
<td>abuse</td>
<td><?=$x_lang_array['abuse']?></td>
<td>abused</td>
<td>abused</td>
</tr>
<tr>
<td>abolish</td>
<td><?=$x_lang_array['abolish']?></td>
<td>abolished</td>
<td>abolished</td>
</tr>
<tr>
<td>avail</td>
<td><?=$x_lang_array['avail']?></td>
<td>availed</td>
<td>availed</td>
</tr>
<tr>
<td>attract</td>
<td><?=$x_lang_array['attract']?></td>
<td>attract</td>
<td>attract</td>
</tr>
<tr>
<td>appoint</td>
<td><?=$x_lang_array['appoint']?></td>
<td>appointed</td>
<td>appointed</td>
</tr>
<tr>
<td>apply</td>
<td><?=$x_lang_array['apply']?></td>
<td>applied</td>
<td>applied</td>
</tr>
<tr>
<td>approve</td>
<td><?=$x_lang_array['approve']?></td>
<td>approved</td>
<td>approved</td>
</tr>
<tr>
<td>accept</td>
<td><?=$x_lang_array['accept']?></td>
<td>accepted</td>
<td>accepted</td>
</tr>
<tr>
<td>accompany</td>
<td><?=$x_lang_array['accompany']?></td>
<td>accompanied</td>
<td>accompanied</td>
</tr>
<tr>
<td>acquire</td>
<td><?=$x_lang_array['acquire']?></td>
<td>acquire</td>
<td>acquired</td>
</tr>
<tr>
<td>annoy</td>
<td><?=$x_lang_array['annoy']?></td>
<td>annoyed</td>
<td>annoyed</td>
</tr>
<tr>
<td>alter</td>
<td><?=$x_lang_array['alter']?></td>
<td>altered</td>
<td>altered</td>
</tr>
<tr>
<td>aim</td>
<td><?=$x_lang_array['aim']?></td>
<td>aimed</td>
<td>aimed</td>
</tr>
<tr>
<td>add</td>
<td><?=$x_lang_array['add']?></td>
<td>added</td>
<td>added</td>
</tr>
<tr>
<td>adapt</td>
<td><?=$x_lang_array['adapt']?></td>
<td>adapted</td>
<td>adapted</td>
</tr>
<tr>
<td>attack</td>
<td><?=$x_lang_array['attack']?></td>
<td>attacked</td>
<td>attacked</td>
</tr>
<tr>
<td>assure</td>
<td><?=$x_lang_array['assure']?></td>
<td>assured</td>
<td>assured</td>
</tr>
<tr>
<td>ask</td>
<td><?=$x_lang_array['ask']?></td>
<td>asked</td>
<td>asked</td>
</tr>
<tr>
<td>ascend</td>
<td><?=$x_lang_array['ascend']?></td>
<td>ascended</td>
<td>ascended</td>
</tr>
<tr>
<td>agree</td>
<td><?=$x_lang_array['agree']?></td>
<td>agreed</td>
<td>agreed</td>
</tr>
<tr>
<td>advise</td>
<td><?=$x_lang_array['advise']?></td>
<td>advised</td>
<td>advised</td>
</tr>
<tr>
<td>adopt</td>
<td><?=$x_lang_array['adopt']?></td>
<td>adopted</td>
<td>adopted</td>
</tr>
<tr>
<td>bend</td>
<td><?=$x_lang_array['bend']?></td>
<td>bent</td>
<td>bent</td>
</tr>
<tr>
<td>believe</td>
<td><?=$x_lang_array['believe']?></td>
<td>believed</td>
<td>believed</td>
</tr>
<tr>
<td>behave</td>
<td><?=$x_lang_array['behave']?></td>
<td>behaved</td>
<td>behaved</td>
</tr>
<tr>
<td>beg</td>
<td><?=$x_lang_array['beg']?></td>
<td>begged</td>
<td>begged</td>
</tr>
<tr>
<td>bleed</td>
<td><?=$x_lang_array['bleed']?></td>
<td>bled</td>
<td>bled</td>
</tr>
<tr>
<td>bring</td>
<td><?=$x_lang_array['bring']?></td>
<td>brought</td>
<td>brought</td>
</tr>
<tr>
<td>charge</td>
<td><?=$x_lang_array['charge']?></td>
<td>charged</td>
<td>charged</td>
</tr>
<tr>
<td>cheat</td>
<td><?=$x_lang_array['cheat']?></td>
<td>cheated</td>
<td>cheated</td>
</tr>
<tr>
<td>compare</td>
<td><?=$x_lang_array['compare']?></td>
<td>compared</td>
<td>compared</td>
</tr>
<tr>
<td>build</td>
<td><?=$x_lang_array['build']?></td>
<td>built</td>
<td>built</td>
</tr>
<tr>
<td>burn</td>
<td><?=$x_lang_array['burn']?></td>
<td>burnt</td>
<td>burnt</td>
</tr>
<tr>
<td>buy</td>
<td><?=$x_lang_array['buy']?></td>
<td>bought</td>
<td>bought</td>
</tr>
<tr>
<td>call</td>
<td><?=$x_lang_array['call']?></td>
<td>called</td>
<td>called</td>
</tr>
<tr>
<td>cry</td>
<td><?=$x_lang_array['cry']?></td>
<td>cried</td>
<td>cried</td>
</tr>
<tr>
<td>deliver</td>
<td><?=$x_lang_array['deliver']?></td>
<td>delivered</td>
<td>delivered</td>
</tr>
<tr>
<td>debar</td>
<td><?=$x_lang_array['debar']?></td>
<td>debarred</td>
<td>debarred</td>
</tr>
<tr>
<td>deal</td>
<td><?=$x_lang_array['deal']?></td>
<td>dealt</td>
<td>dealt</td>
</tr>
<tr>
<td>dare</td>
<td><?=$x_lang_array['dare']?></td>
<td>dared</td>
<td>dared</td>
</tr>
<tr>
<td>catch</td>
<td><?=$x_lang_array['catch']?></td>
<td>caught</td>
<td>caught</td>
</tr>
<tr>
<td>cook</td>
<td><?=$x_lang_array['cook']?></td>
<td>cooked</td>
<td>cooked</td>
</tr>
<tr>
<td>creep</td>
<td><?=$x_lang_array['creep']?></td>
<td>crept</td>
<td>crept</td>
</tr>
<tr>
<td>change</td>
<td><?=$x_lang_array['change']?></td>
<td>changed</td>
<td>changed</td>
</tr>
<tr>
<td>complain</td>
<td><?=$x_lang_array['complain']?></td>
<td>complained</td>
<td>complained</td>
</tr>
<tr>
<td>compose</td>
<td><?=$x_lang_array['compose']?></td>
<td>composed</td>
<td>composed</td>
</tr>
<tr>
<td>convict</td>
<td><?=$x_lang_array['convict']?></td>
<td>convicted</td>
<td>convicted</td>
</tr>
<tr>
<td>cure</td>
<td><?=$x_lang_array['cure']?></td>
<td>cured</td>
<td>cured</td>
</tr>
<tr>
<td>decide</td>
<td><?=$x_lang_array['decide']?></td>
<td>decided</td>
<td>decided</td>
</tr>
<tr>
<td>dedicate</td>
<td><?=$x_lang_array['dedicate']?></td>
<td>dedicated</td>
<td>dedicated</td>
</tr>
<tr>
<td>hear</td>
<td><?=$x_lang_array['hear']?></td>
<td>heard</td>
<td>heard</td>
</tr>
<tr>
<td>hate</td>
<td><?=$x_lang_array['hate']?></td>
<td>hated</td>
<td>hated</td>
</tr>
<tr>
<td>have</td>
<td><?=$x_lang_array['have']?></td>
<td>had</td>
<td>had</td>
</tr>
<tr>
<td>hang</td>
<td><?=$x_lang_array['hang']?></td>
<td>hanged</td>
<td>hanged</td>
</tr>
<tr>
<td>demand</td>
<td><?=$x_lang_array['demand']?></td>
<td>demanded</td>
<td>demanded</td>
</tr>
<tr>
<td>deny</td>
<td><?=$x_lang_array['deny']?></td>
<td>denied</td>
<td>denied</td>
</tr>
<tr>
<td>depend</td>
<td><?=$x_lang_array['depend']?></td>
<td>depended</td>
<td>depended</td>
</tr>
<tr>
<td>destroy</td>
<td><?=$x_lang_array['destroy']?></td>
<td>destroyed</td>
<td>destroyed</td>
</tr>
<tr>
<td>gather</td>
<td><?=$x_lang_array['gather']?></td>
<td>gathered</td>
<td>gathered</td>
</tr>
<tr>
<td>gaze</td>
<td><?=$x_lang_array['gaze']?></td>
<td>gazed</td>
<td>gazed</td>
</tr>
<tr>
<td>flee</td>
<td><?=$x_lang_array['flee']?></td>
<td>fled</td>
<td>fled</td>
</tr>
<tr>
<td>feel</td>
<td><?=$x_lang_array['feel']?></td>
<td>felt</td>
<td>felt</td>
</tr>
<tr>
<td>feed</td>
<td><?=$x_lang_array['feed']?></td>
<td>fed</td>
<td>fed</td>
</tr>
<tr>
<td>determine</td>
<td><?=$x_lang_array['determine']?></td>
<td>determined</td>
<td>determined</td>
</tr>
<tr>
<td>deviate</td>
<td><?=$x_lang_array['deviate']?></td>
<td>deviated</td>
<td>deviated</td>
</tr>
<tr>
<td>die</td>
<td><?=$x_lang_array['die']?></td>
<td>died</td>
<td>died</td>
</tr>
<tr>
<td>dream</td>
<td><?=$x_lang_array['dream']?></td>
<td>dreamt</td>
<td>dreamt</td>
</tr>
<tr>
<td>divide</td>
<td><?=$x_lang_array['divide']?></td>
<td>divided</td>
<td>divided</td>
</tr>
<tr>
<td>inform</td>
<td><?=$x_lang_array['inform']?></td>
<td>informed</td>
<td>informed</td>
</tr>
<tr>
<td>inspire</td>
<td><?=$x_lang_array['inspire']?></td>
<td>inspired</td>
<td>inspired</td>
</tr>
<tr>
<td>introduce</td>
<td><?=$x_lang_array['introduce']?></td>
<td>introduced</td>
<td>introduced</td>
</tr>
<tr>
<td>embellish</td>
<td><?=$x_lang_array['embellish']?></td>
<td>embellished</td>
<td>embellished</td>
</tr>
<tr>
<td>enter</td>
<td><?=$x_lang_array['enter']?></td>
<td>entered</td>
<td>entered</td>
</tr>
<tr>
<td>expressed</td>
<td><?=$x_lang_array['expressed']?></td>
<td>expressed</td>
<td>expressed</td>
</tr>
<tr>
<td>maintain</td>
<td><?=$x_lang_array['maintain']?></td>
<td>maintained</td>
<td>maintained</td>
</tr>
<tr>
<td>marry</td>
<td><?=$x_lang_array['marry']?></td>
<td>married</td>
<td>married</td>
</tr>
<tr>
<td>make</td>
<td><?=$x_lang_array['make']?></td>
<td>made</td>
<td>made</td>
</tr>
<tr>
<td>insist</td>
<td><?=$x_lang_array['insist']?></td>
<td>insisted</td>
<td>insisted</td>
</tr>
<tr>
<td>invade</td>
<td><?=$x_lang_array['invade']?></td>
<td>invaded</td>
<td>invaded</td>
</tr>
<tr>
<td>invite</td>
<td><?=$x_lang_array['invite']?></td>
<td>invited</td>
<td>invited</td>
</tr>
<tr>
<td>involve</td>
<td><?=$x_lang_array['involve']?></td>
<td>involved</td>
<td>involved</td>
</tr>
<tr>
<td>lose</td>
<td><?=$x_lang_array['lose']?></td>
<td>lost</td>
<td>lost</td>
</tr>
<tr>
<td>look</td>
<td><?=$x_lang_array['look']?></td>
<td>looked</td>
<td>looked</td>
</tr>
<tr>
<td>like</td>
<td><?=$x_lang_array['like']?></td>
<td>liked</td>
<td>liked</td>
</tr>
<tr>
<td>light</td>
<td><?=$x_lang_array['light']?></td>
<td>lighted</td>
<td>lighted</td>
</tr>
<tr>
<td>lie</td>
<td><?=$x_lang_array['lie']?></td>
<td>lied</td>
<td>lied</td>
</tr>
<tr>
<td>joke</td>
<td><?=$x_lang_array['joke']?></td>
<td>joked</td>
<td>joked</td>
</tr>
<tr>
<td>keep</td>
<td><?=$x_lang_array['keep']?></td>
<td>kept</td>
<td>kept</td>
</tr>
<tr>
<td>kill</td>
<td><?=$x_lang_array['kill']?></td>
<td>killed</td>
<td>killed</td>
</tr>
<tr>
<td>kneel</td>
<td><?=$x_lang_array['kneel']?></td>
<td>knelt</td>
<td>knelt</td>
</tr>
<tr>
<td>laugh</td>
<td><?=$x_lang_array['laugh']?></td>
<td>laughed</td>
<td>laughed</td>
</tr>
<tr>
<td>lend</td>
<td><?=$x_lang_array['lend']?></td>
<td>lent</td>
<td>lent</td>
</tr>
<tr>
<td>leave</td>
<td><?=$x_lang_array['leave']?></td>
<td>left</td>
<td>left</td>
</tr>
<tr>
<td>learn</td>
<td><?=$x_lang_array['learn']?></td>
<td>learnt</td>
<td>learnt</td>
</tr>
<tr>
<td>lead</td>
<td><?=$x_lang_array['lead']?></td>
<td>led</td>
<td>led</td>
</tr>
<tr>
<td>lay</td>
<td><?=$x_lang_array['lay']?></td>
<td>laid</td>
<td>laid</td>
</tr>
<tr>
<td>owe</td>
<td><?=$x_lang_array['owe']?></td>
<td>owed</td>
<td>owed</td>
</tr>
<tr>
<td>order</td>
<td><?=$x_lang_array['order']?></td>
<td>ordered</td>
<td>ordered</td>
</tr>
<tr>
<td>omit</td>
<td><?=$x_lang_array['omit']?></td>
<td>omitted</td>
<td>omitted</td>
</tr>
<tr>
<td>occur</td>
<td><?=$x_lang_array['occur']?></td>
<td>occurred</td>
<td>occurred</td>
</tr>
<tr>
<td>observe</td>
<td><?=$x_lang_array['observe']?></td>
<td>observed</td>
<td>observed</td>
</tr>
<tr>
<td>open</td>
<td><?=$x_lang_array['open']?></td>
<td>opened</td>
<td>opened</td>
</tr>
<tr>
<td>occupy</td>
<td><?=$x_lang_array['occupy']?></td>
<td>occupied</td>
<td>occupied</td>
</tr>
<tr>
<td>pray</td>
<td><?=$x_lang_array['pray']?></td>
<td>prayed</td>
<td>prayed</td>
</tr>
<tr>
<td>punish</td>
<td><?=$x_lang_array['punish']?></td>
<td>punished</td>
<td>punished</td>
</tr>
<tr>
<td>play</td>
<td><?=$x_lang_array['play']?></td>
<td>played</td>
<td>played</td>
</tr>
<tr>
<td>pay</td>
<td><?=$x_lang_array['pay']?></td>
<td>paid</td>
<td>paid</td>
</tr>
<tr>
<td>preside</td>
<td><?=$x_lang_array['preside']?></td>
<td>presided</td>
<td>presided</td>
</tr>
<tr>
<td>prevent</td>
<td><?=$x_lang_array['prevent']?></td>
<td>prevented</td>
<td>prevented</td>
</tr>
<tr>
<td>negotiate</td>
<td><?=$x_lang_array['negotiate']?></td>
<td>negotiated</td>
<td>negotiated</td>
</tr>
<tr>
<td>mow</td>
<td><?=$x_lang_array['mow']?></td>
<td>mowed</td>
<td>mowed</td>
</tr>
<tr>
<td>move</td>
<td><?=$x_lang_array['move']?></td>
<td>moved</td>
<td>moved</td>
</tr>
<tr>
<td>mix</td>
<td><?=$x_lang_array['mix']?></td>
<td>mixed</td>
<td>mixed</td>
</tr>
<tr>
<td>mend</td>
<td><?=$x_lang_array['mend']?></td>
<td>mended</td>
<td>mended</td>
</tr>
<tr>
<td>meet</td>
<td><?=$x_lang_array['meet']?></td>
<td>met</td>
<td>met</td>
</tr>
<tr>
<td>mean</td>
<td><?=$x_lang_array['mean']?></td>
<td>meant</td>
<td>meant</td>
</tr>
<tr>
<td>manage</td>
<td><?=$x_lang_array['manage']?></td>
<td>managed</td>
<td>managed</td>
</tr>
<tr>
<td>prepare</td>
<td><?=$x_lang_array['prepare']?></td>
<td>prepared</td>
<td>prepared</td>
</tr>
<tr>
<td>preserve</td>
<td><?=$x_lang_array['preserve']?></td>
<td>preserve</td>
<td>preserved</td>
</tr>
<tr>
<td>pretend</td>
<td><?=$x_lang_array['pretend']?></td>
<td>pretended</td>
<td>pretended</td>
</tr>
<tr>
<td>proceed</td>
<td><?=$x_lang_array['proceed']?></td>
<td>proceeded</td>
<td>proceeded</td>
</tr>
<tr>
<td>prohibit</td>
<td><?=$x_lang_array['prohibit']?></td>
<td>prohibited</td>
<td>prohited</td>
</tr>
<tr>
<td>reject</td>
<td><?=$x_lang_array['reject']?></td>
<td>rejected</td>
<td>rejected</td>
</tr>
<tr>
<td>rehabilitate</td>
<td><?=$x_lang_array['rehabilitate']?></td>
<td>rehabilitated</td>
<td>rehabilitated</td>
</tr>
<tr>
<td>refuse</td>
<td><?=$x_lang_array['refuse']?></td>
<td>refused</td>
<td>refused</td>
</tr>
<tr>
<td>refund</td>
<td><?=$x_lang_array['refund']?></td>
<td>refunded</td>
<td>refunded</td>
</tr>
<tr>
<td>recover</td>
<td><?=$x_lang_array['recover']?></td>
<td>recovered</td>
<td>recovered</td>
</tr>
<tr>
<td>propose</td>
<td><?=$x_lang_array['propose']?></td>
<td>proposed</td>
<td>proposed</td>
</tr>
<tr>
<td>prosecute</td>
<td><?=$x_lang_array['prosecute']?></td>
<td>prosecuted</td>
<td>prosecuted</td>
</tr>
<tr>
<td>prove</td>
<td><?=$x_lang_array['prove']?></td>
<td>proved</td>
<td>proved</td>
</tr>
<tr>
<td>persist</td>
<td><?=$x_lang_array['persist']?></td>
<td>persisted</td>
<td>persisted</td>
</tr>
<tr>
<td>realize</td>
<td><?=$x_lang_array['realize']?></td>
<td>realized</td>
<td>realized</td>
</tr>
<tr>
<td>raise</td>
<td><?=$x_lang_array['raise']?></td>
<td>raised</td>
<td>raised</td>
</tr>
<tr>
<td>receive</td>
<td><?=$x_lang_array['receive']?></td>
<td>received</td>
<td>received</td>
</tr>
<tr>
<td>reach</td>
<td><?=$x_lang_array['reach']?></td>
<td>reached</td>
<td>reached</td>
</tr>
<tr>
<td>read</td>
<td><?=$x_lang_array['read']?></td>
<td>read</td>
<td>read</td>
</tr>
<tr>
<td>quarrel</td>
<td><?=$x_lang_array['quarrel']?></td>
<td>quarrelled</td>
<td>quarrelled</td>
</tr>
<tr>
<td>say</td>
<td><?=$x_lang_array['say']?></td>
<td>said</td>
<td>said</td>
</tr>
<tr>
<td>sew</td>
<td><?=$x_lang_array['sew']?></td>
<td>sewed</td>
<td>sewed</td>
</tr>
<tr>
<td>seek</td>
<td><?=$x_lang_array['seek']?></td>
<td>sought</td>
<td>sought</td>
</tr>
<tr>
<td>remind</td>
<td><?=$x_lang_array['remind']?></td>
<td>reminded</td>
<td>reminded</td>
</tr>
<tr>
<td>remit</td>
<td><?=$x_lang_array['remit']?></td>
<td>remitted</td>
<td>remitted</td>
</tr>
<tr>
<td>return</td>
<td><?=$x_lang_array['return']?></td>
<td>returned</td>
<td>returned</td>
</tr>
<tr>
<td>respond</td>
<td><?=$x_lang_array['respond']?></td>
<td>responded</td>
<td>responded</td>
</tr>
<tr>
<td>rob</td>
<td><?=$x_lang_array['rob']?></td>
<td>robbed</td>
<td>robbed</td>
</tr>
<tr>
<td>repair</td>
<td><?=$x_lang_array['repair']?></td>
<td>repaired</td>
<td>repaired</td>
</tr>
<tr>
<td>reply</td>
<td><?=$x_lang_array['reply']?></td>
<td>replied</td>
<td>replied</td>
</tr>
<tr>
<td>rescue</td>
<td><?=$x_lang_array['rescue']?></td>
<td>rescued</td>
<td>rescued</td>
</tr>
<tr>
<td>swell</td>
<td><?=$x_lang_array['swell']?></td>
<td>swelled</td>
<td>swelled</td>
</tr>
<tr>
<td>sell</td>
<td><?=$x_lang_array['sell']?></td>
<td>sold</td>
<td>sold</td>
</tr>
<tr>
<td>sweep</td>
<td><?=$x_lang_array['sweep']?></td>
<td>swept</td>
<td>swept</td>
</tr>
<tr>
<td>send</td>
<td><?=$x_lang_array['send']?></td>
<td>sent</td>
<td>sent</td>
</tr>
<tr>
<td>shoot</td>
<td><?=$x_lang_array['shoot']?></td>
<td>shot</td>
<td>shot</td>
</tr>
<tr>
<td>spoil</td>
<td><?=$x_lang_array['spoil']?></td>
<td>spoiled</td>
<td>spoiled</td>
</tr>
<tr>
<td>sleep</td>
<td><?=$x_lang_array['sleep']?></td>
<td>slept</td>
<td>slept</td>
</tr>
<tr>
<td>show</td>
<td><?=$x_lang_array['show']?></td>
<td>showed</td>
<td>showed</td>
</tr>
<tr>
<td>sow</td>
<td><?=$x_lang_array['sow']?></td>
<td>sowed</td>
<td>sowed</td>
</tr>
<tr>
<td>stay</td>
<td><?=$x_lang_array['stay']?></td>
<td>stayed</td>
<td>stayed</td>
</tr>
<tr>
<td>spend</td>
<td><?=$x_lang_array['spend']?></td>
<td>spent</td>
<td>spent</td>
</tr>
<tr>
<td>work</td>
<td><?=$x_lang_array['work']?></td>
<td>worked</td>
<td>worked</td>
</tr>
<tr>
<td>wish</td>
<td><?=$x_lang_array['wish']?></td>
<td>wished</td>
<td>wished</td>
</tr>
<tr>
<td>wait</td>
<td><?=$x_lang_array['wait']?></td>
<td>waited</td>
<td>waited</td>
</tr>
<tr>
<td>warn</td>
<td><?=$x_lang_array['warn']?></td>
<td>warned</td>
<td>warned</td>
</tr>
<tr>
<td>smile</td>
<td><?=$x_lang_array['smile']?></td>
<td>smiled</td>
<td>smiled</td>
</tr>
<tr>
<td>smell</td>
<td><?=$x_lang_array['smell']?></td>
<td>smelt</td>
<td>smelt</td>
</tr>
<tr>
<td>teach</td>
<td><?=$x_lang_array['teach']?></td>
<td>taught</td>
<td>taught</td>
</tr>
<tr>
<td>want</td>
<td><?=$x_lang_array['want']?></td>
<td>wanted</td>
<td>wanted</td>
</tr>
<tr>
<td>walk</td>
<td><?=$x_lang_array['walk']?></td>
<td>walked</td>
<td>walked</td>
</tr>
<tr>
<td>visit</td>
<td><?=$x_lang_array['visit']?></td>
<td>visited</td>
<td>visited</td>
</tr>
<tr>
<td>vanish</td>
<td><?=$x_lang_array['vanish']?></td>
<td>vanished</td>
<td>vanished</td>
</tr>
<tr>
<td>tell</td>
<td><?=$x_lang_array['tell']?></td>
<td>told</td>
<td>told</td>
</tr>
<tr>
<td>think</td>
<td><?=$x_lang_array['think']?></td>
<td>thought</td>
<td>thought</td>
</tr>
<tr>
<td>travel</td>
<td><?=$x_lang_array['travel']?></td>
<td>travelled</td>
<td>travelled</td>
</tr>
<tr>
<td>tremble</td>
<td><?=$x_lang_array['tremble']?></td>
<td>trembled</td>
<td>trembled</td>
</tr>
<tr>
<td>utter</td>
<td><?=$x_lang_array['utter']?></td>
<td>uttered</td>
<td>uttered</td>
</tr>
<tr>
<td>unite</td>
<td><?=$x_lang_array['unite']?></td>
<td>united</td>
<td>united</td>
</tr>
<tr>
<td>twinkle</td>
<td><?=$x_lang_array['twinkle']?></td>
<td>twinkled</td>
<td>twinkled</td>
</tr>
<tr>
<td>treat</td>
<td><?=$x_lang_array['treat']?></td>
<td>treated</td>
<td>treated</td>
</tr>
<tr>
<td>bend</td>
<td><?=$x_lang_array['bend']?></td>
<td>bent</td>
<td>bent</td>
</tr>
<tr>
<td>breed</td>
<td><?=$x_lang_array['breed']?></td>
<td>bred</td>
<td>bred</td>
</tr>
<tr>
<td>clothe</td>
<td><?=$x_lang_array['clothe']?></td>
<td>clothed</td>
<td>clothed</td>
</tr>
<tr>
<td>gird</td>
<td><?=$x_lang_array['gird']?></td>
<td>girded,girt</td>
<td>girded,girt</td>
</tr>
<tr>
<td>hew</td>
<td><?=$x_lang_array['hew']?></td>
<td>hewed</td>
<td>hewed</td>
</tr>
<tr>
<td>lean</td>
<td><?=$x_lang_array['lean']?></td>
<td>leant</td>
<td>leant</td>
</tr>
<tr>
<td>load</td>
<td><?=$x_lang_array['load']?></td>
<td>loaded</td>
<td>loaded</td>
</tr>
<tr>
<td>melt</td>
<td><?=$x_lang_array['melt']?></td>
<td>melted</td>
<td>melted</td>
</tr>
<tr>
<td>rend</td>
<td><?=$x_lang_array['rend']?></td>
<td>rent</td>
<td>rent</td>
</tr>
<tr>
<td>spell</td>
<td><?=$x_lang_array['spell']?></td>
<td>spelled,spelt</td>
<td>spelled,spelt</td>
</tr>
<tr>
<td>knock</td>
<td><?=$x_lang_array['knock']?></td>
<td>knocked</td>
<td>knocked</td>
</tr>
<tr>
<td>repeat</td>
<td><?=$x_lang_array['repeat']?></td>
<td>repeated</td>
<td>repeated</td>
</tr>
<tr>
<td>pick</td>
<td><?=$x_lang_array['pick']?></td>
<td>picked</td>
<td>picked</td>
</tr>
<tr>
<td>join</td>
<td><?=$x_lang_array['join']?></td>
<td>joined</td>
<td>joined</td>
</tr>
<tr>
<td>clean</td>
<td><?=$x_lang_array['clean']?></td>
<td>cleaned</td>
<td>cleaned</td>
</tr>
<tr>
<td>match</td>
<td><?=$x_lang_array['match']?></td>
<td>matched</td>
<td>matched</td>
</tr>
<tr>
<td>offer</td>
<td><?=$x_lang_array['offer']?></td>
<td>offered</td>
<td>offered</td>
</tr>
<tr>
<td>plunge</td>
<td><?=$x_lang_array['plunge']?></td>
<td>plunged</td>
<td>plunged</td>
</tr>
<tr>
<td>watch</td>
<td><?=$x_lang_array['watch']?></td>
<td>watched</td>
<td>watched</td>
</tr>
<tr>
<td>slip</td>
<td><?=$x_lang_array['slip']?></td>
<td>slipped</td>
<td>slipped</td>
</tr>
<tr>
<td>chatter</td>
<td><?=$x_lang_array['chatter']?></td>
<td>chattered</td>
<td>chattered</td>
</tr>
<tr>
<td>shock</td>
<td><?=$x_lang_array['shock']?></td>
<td>shocked</td>
<td>shocked</td>
</tr>
<tr>
<td>shook</td>
<td><?=$x_lang_array['shook']?></td>
<td>shooked</td>
<td>shooked</td>
</tr>
<tr>
<td>affect</td>
<td><?=$x_lang_array['affect']?></td>
<td>affected</td>
<td>affected</td>
</tr>
<tr>
<td>last</td>
<td><?=$x_lang_array['last']?></td>
<td>lasted</td>
<td>lasted</td>
</tr>
<tr>
<td>plan</td>
<td><?=$x_lang_array['plan']?></td>
<td>planned</td>
<td>planned</td>
</tr>
<tr>
<td>expose</td>
<td><?=$x_lang_array['expose']?></td>
<td>exposed</td>
<td>exposed</td>
</tr>
<tr>
<td>tip</td>
<td><?=$x_lang_array['tip']?></td>
<td>tipped</td>
<td>tipped</td>
</tr>
<tr>
<td>need</td>
<td><?=$x_lang_array['need']?></td>
<td>needed</td>
<td>needed</td>
</tr>
<tr>
<td>suit</td>
<td><?=$x_lang_array['suit']?></td>
<td>suited</td>
<td>suited</td>
</tr>
<tr>
<td>fold</td>
<td><?=$x_lang_array['fold']?></td>
<td>folded</td>
<td>folded</td>
</tr>
<tr>
<td>decorate</td>
<td><?=$x_lang_array['decorate']?></td>
<td>decorated</td>
<td>decorated</td>
</tr>
<tr>
<td>disappear</td>
<td><?=$x_lang_array['disappear']?></td>
<td>disappeared</td>
<td>disappeared</td>
</tr>
<tr>
<td>plough</td>
<td><?=$x_lang_array['plough']?></td>
<td>ploughed</td>
<td>ploughed</td>
</tr>
<tr>
<td>ban</td>
<td><?=$x_lang_array['ban']?></td>
<td>banned</td>
<td>banned</td>
</tr>
<tr>
<td>protect</td>
<td><?=$x_lang_array['protect']?></td>
<td>protected</td>
<td>protected</td>
</tr>
<tr>
<td>reproduce</td>
<td><?=$x_lang_array['reproduce']?></td>
<td>reproduced</td>
<td>reproduced</td>
</tr>
<tr>
<td>contain</td>
<td><?=$x_lang_array['contain']?></td>
<td>contained</td>
<td>contained</td>
</tr>
<tr>
<td>stretch</td>
<td><?=$x_lang_array['stretch']?></td>
<td>stretched</td>
<td>stretched</td>
</tr>
<tr>
<td>notice</td>
<td><?=$x_lang_array['notice']?></td>
<td>noticed</td>
<td>noticed</td>
</tr>
</tbody>
</table>						

							
                        </div>	
                    </fieldset>
                </div>

            </div>
            
            <?php include('right-content.php');?>

        </div>

<?php include('footer.php');?>