(function() {
var e=null,g,i={Xb:44032,Wb:4352,Yb:4449,ea:4519,$b:21,Ea:28};i.Zb=i.$b*i.Ea;i.eb="\u1100,\u1101,\u1100\u1109,\u1102,\u1102\u110c,\u1102\u1112,\u1103,\u1105,\u1105\u1100,\u1105\u1106,\u1105\u1107,\u1105\u1109,\u1105\u1110,\u1105\u1111,\u1105\u1112,\u1106,\u1107,\u1107\u1109,\u1109,\u110a,\u110b,\u110c,\u110e,\u110f,\u1110,\u1111,\u1112,\u1100\u1105".split(",");i.cc={"\u1104":"\u1104","\u1108":"\u1108","\u110d":"\u110d"};for(var r=0;r<i.eb.length;r++)i.cc[i.eb[r]]=String.fromCharCode(i.ea+1+r);
i.Pd={"\u1169\u1161":"\u116a","\u1169\u1162":"\u116b","\u1169\u1175":"\u116c","\u116e\u1165":"\u116f","\u116e\u1166":"\u1170","\u116e\u1175":"\u1171","\u1173\u1175":"\u1174"};i.Fd=/[\u11a8-\u11c3]/g;i.Md=/\u1169\u1161|\u1169\u1162|\u1169\u1175|\u116e\u1165|\u116e\u1166|\u116e\u1175|\u1173\u1175/g;i.Kd=/[\uac00-\ud7af]/g;i.Ld=/([\u1100-\u1112][\u1161-\u1175][\u11a7-\u11c3]?)/g;i.ia="[\u1161-\u1175]";i.ha="[\u1100-\u1112]";i.Rd="\u1100\u1109|\u1102\u110c|\u1102\u1112|\u1105\u1100|\u1105\u1107|\u1105\u1109|\u1105\u1110|\u1105\u1111|\u1105\u1112|\u1107\u1109";
i.bc="([^\u1161-\u1175]|$)";i.Sd="([^\u1100-\u1112\u1161-\u1175]|$)";i.ud=RegExp("("+i.ia+")("+i.ha+")("+i.ha+i.ia+")");i.sd=RegExp("("+i.ia+")("+i.Rd+")("+i.bc+")");i.td=RegExp("("+i.ia+")("+i.ha+")("+i.ha+i.bc+")");i.vd=RegExp("("+i.ia+")("+i.ha+")("+i.Sd+")");i.Od=function(a){var c=a.charCodeAt(0)-i.Xb,a=i.Wb+c/i.Zb,k=i.Yb+c%i.Zb/i.Ea,c=i.ea+c%i.Ea;return String.fromCharCode(a)+String.fromCharCode(k)+(c==i.ea?"":String.fromCharCode(c))};
i.xd=function(a){return a.replace(i.Fd,function(a){return i.eb[a.charCodeAt(0)-i.ea-1]})};i.wd=function(a){return a.replace(i.Md,function(a){return i.Pd[a]})};i.Id=function(a){return a.replace(i.Kd,i.Od)};i.Nd=function(a){var c=a.charCodeAt(0)-i.Wb,k=a.charCodeAt(1)-i.Yb,a=a.length>=3?a.charCodeAt(2)-i.ea:0;return String.fromCharCode((c*i.$b+k)*i.Ea+a+i.Xb)};i.Hd=function(a){return a.replace(i.Ld,i.Nd)};i.Fa=function(a,c,k,h){return c+i.cc[k]+h};
i.Jd=function(a){return i.wd(i.xd(a)).replace(i.ud,i.Fa).replace(i.sd,i.Fa).replace(i.td,i.Fa).replace(i.vd,i.Fa)};i.Xd=function(a){return i.Hd(i.Jd(i.Id(a.replace("\u001d",""))))};var ba=!0,s=typeof unsafeWindow=="undefined"?window:unsafeWindow,w,A,B;function ca(a){return document.getElementById(a)}function da(a){return document.all[a]}var K=document.getElementById?ca:da,N={};function ea(a,c){for(var k=c||document,h=k.childNodes,d=0;d<h.length;d++){var u=h[d];if(u===a)return k.removeChild(a),!0}for(d=0;d<h.length;d++)if((u=h[d])&&ea(a,u))return!0;return!1}function fa(a){if(!a)return-1;var c=a.offsetHeight,a=a.clip;return c||(a?a.height:-1)}var O=0,P=0,Q=0,ga=0;if(s.Event)O=Event.ALT_MASK,P=Event.CONTROL_MASK,Q=Event.ALT_MASK,ga=Event.SHIFT_MASK;var ja=O|P|Q,S={};S.userAgent=navigator.userAgent.toLowerCase();S.xa=S.userAgent.indexOf("msie")>0&&!window.opera;
S.z=S.userAgent.indexOf("firefox")>=0;var ka,T=S.userAgent.match(/firefox\/(\d+)/);ka=!T||T.length!=2?-1:parseInt(T[1],10);S.Cb=ka;var la,U=S.userAgent.match(/msie (\d+)/);la=!U||U.length!=2?-1:parseInt(U[1],10);S.Uc=la;S.q=S.userAgent.indexOf("applewebkit")>-1;S.Db=S.userAgent.indexOf("windows")>-1;var ma={en:"",fr:"",de:""},na=S.q?91:224;
S.j=function(a,c,k){function h(b){var a=n!=b;n=b;a&&f.la();return a}function d(b){for(var a=0;a<arguments.length;a++)W.push(arguments[a])}function u(b){b&&d('<td style="width:',b,'px"/>')}function q(b){d('<table style="margin-left:auto;margin-right:auto;empty-cells:show;border-collapse:collapse" border="0" cellspacing="0" cellpadding="1px"><tr align="center">');b&&u(b)}function m(b){u(b);d("</tr></table>\n")}function b(b,a,j,o,c){c=c||"";b=b.charCodeAt(0);f.T[b]=void 0;b="K"+b;d('<td style="');d("margin:0;");
d("width:",j,'px">');if(a){c=f.za+" "+c+" ";d("<input type=button");d(' class="',c,'"');d(' id="',b,'"');d(' name="',b,'"');S.Uc==8&&d(' style="filter:;background=#eee;border-style:outset;"');if(a!="\x00"){d(' value="');b=d;c=[];for(j=0;j<a.length;j++){var o=a.charAt(j),x=a.charCodeAt(j);c.push("\\'\"".indexOf(o)>=0||x>127||x<33?"&#"+x+";":o)}a=c.join("");b(a);d('"')}S.a.B&&d(' dir="rtl"');d("/>")}else d("<button"),d(" name=",b),d(" type=button"),d(' class="',f.za,' goog-button-icon-c"'),d(">"),d("<span"),
d(' class="goog-button-icon ',c,'"'),d(' id="BG',b,'"'),d(">&nbsp"),d("</span>"),d("</button>");d("</td>")}function t(a,j){for(var o=0;o<a.length;o++){var f=a.charAt(o),d=j&&o==a.length-1?j:1;b(f,f,d*24)}}function v(){f.b&&f.b.Pc()}function C(b){return function(a){b(this,a);a&&!a.type&&oa(this)}}function l(b){return b=f.T[b]}function x(b){return(b=f.T[b])&&b.length?b[0]:b}function y(b,a){if(b&&b.className)b.className=b.className.replace(/ goog-button-active/g,""),a&&(b.className+=" goog-button-active")}
function D(){h(n^2);S.a.g()}function p(b){if(b==((n&1)==1))return!0;b=b?1:0;h(n&-2|b);S.a.g();return!1}function G(b){h(b||(n&12)!=12?n|12:n&-13);S.a.g()}function H(b){var b=b.which||b.keyCode||b.charCode,a=pa[f.r];a&&(b=a[String.fromCharCode(b)]||b);return qa[b]||b}function z(b){return function(a){a=a||s.event;return a.returnValue=b(a)}}function E(){return N.H?S.a&&S.a.fb():S.a&&S.a.lc()}function j(b,a){if(!L){var j=a==16||b&&(b.shiftKey||b.modifiers&ga)?1:0;h(n&-2|j)}L=!1;M||(j=a==17||b&&(b.ctrlKey||
b.modifiers&P)?4:0,h(n&-5|j),j=a==18||b&&(b.altKey||b.modifiers&Q)?8:0,h(n&-9|j));M=!1}function o(b,a){X=!0;I=b;var j=x(b);if(j){var o=s._kbdSI;a&&o&&f.za!=a.className&&o(a);S.a.g();j.onclick.call(j,!0)}else J=!1;return!j}function oa(b){var a=b.className;y(b,!0);b.Jb=b.Jb||function(){b.className=a};s.setTimeout(b.Jb,250)}var f=this,W=[],n=0;f.re=function(){return n};var J=!1,L=!1,M=!1,X=!1,I=-1;f.ka="";var F=k;f.v=[];f.te=a;f.L=1;f.gb=1;f.T={};f.r="en";f.Yc=0;f.$c=0;f.Zc=0;f.Kb=0;f.ka=F?F.id:"??";
var ra=["\u00c01234567890m=","QWERTYUIOP\u00db\u00dd\u00dc","ASDFGHJKL;\u00de","ZXCVBNM\u00bc\u00be\u00bf",""],sa=["\u00c01234567890m=","QWERTYUIOP\u00db\u00dd","ASDFGHJKL;\u00de\u00dc","\u00e2ZXCVBNM\u00bc\u00be\u00bf",""],Y={"~":192,_:109,"+":61,"|":220,":":59,"<":188,">":190,"?":191},pa={de:{Y:90,Z:89,"\u00dc":192,"\u00db":109,"\u00dd":61,";":219,"=":221,"\u00bf":220,"\u00cc":59,m:191},fr:{Q:65,A:81,Z:87,W:90,"\u00dd":219,"\u00ba":221,M:59,"\u00c0":222,"\u00de":192,"\u00bc":77,"\u00be":188,"\u00bf":190,
"\u00df":191,"\u00db":109}},qa={189:109,187:61,107:61,186:59},ha="endefr";f.xe=h;f.pc=function(b){f.r=b;f.na();S.a.K()};f.Xa=function(){return S.a.ic&&S.a.c&&S.a.kb()};f.Xc=function(){var a=f.b.I?sa:ra;f.Wa="";W=['<form style="margin-bottom:0" action="">'];q();t(a[0]);b("\u0008","",48);q(36);f.b.I?(t(a[1]),f.Xa()?b("\n","",36):m(36)):t(a[1],1.5);q();b("\u0014","",48);t(a[2]);f.b.I?f.Xa()?b("\n","",24,1,"short"):m(24):f.Xa()?b("\n","",48,1,"long"):m(48);q();f.b.I?b("\u0010","",36,1,"shortleft"):b("\u0010",
"",60,1,"left");t(a[3]);b("\u0010","",60,1,"right");S.a.jc&&(q(),b("\u0111","Alt+Ctrl",72),b(" ","&nbsp",236),b("\u0111","Alt+Ctrl",72));d("</form>");f.Wa=W.join("")};f.oc=function(){return ha.indexOf(f.r)+f.v.join("")};f.ec=function(b){if(b){var a=b.charCodeAt(0)-48,b=b.substring(b.length-2);f.r=ha.substring(a,a+2);f.k(b)}else f.k(F?F.p():"??")};f.se=function(){return function(b){S.a.k(b.id)}};f.Ja=function(b){F=b};f.k=function(b){var a;if(b)a=c[b]||c[b.toUpperCase()]||c[b.substring(0,2).toUpperCase()],
f.ka=b;a?f.b&&f.b.p()==b||a.Tc()&&S.a.N(a):(f.ka=F?F.p():"??",S.a.N(F))};f.na=function(){var b=f.r=="en"?"":ma[f.r];if(f.b)S.a.jb(f.b.Ua(),f.b.Sc(),b);else{var a="(loading...)";S.a.jb(a,a,b)}};f.N=function(b){if(f.b!=b){v();f.b=b;f.na();f.la();for(var b=b.p(),a=0;a<f.v.length;a++)f.v[a]==b&&f.v.splice(a,1);f.v.push(b);f.v.length>S.a.kc&&f.v.shift()}};f.fc=function(){f.na();S.a.ib(f.Wa)};f.za="goog-button goog-button-fixed";var ia=S.userAgent.indexOf("linux")>-1,R=S.userAgent.indexOf("mac")>-1;f.Va=
function(b){return f.b&&f.b.Ib?f.b.Va(b):{Ia:b}};f.Wc=function(b,a){var j=f.b.Qc();return a>=j.length&&b.lastIndexOf(j,a-j.length)==a-j.length};var ta={back:1,Ia:""},ua={K8:function(){if(f.b){var b=f.b.d[f.b.d.length-1],a=b.e,b=b.i,a=a.slice(0,a.length-1);b>a.length&&(b=-1);f.b.d=[{e:a,i:b,o:"",u:0,f:""}]}a=ta;f.Kb++;S.a.ma(a)},K10:function(){S.a.mc();v()},K16:function(){L=!L;p((n&1)!=1)},K20:function(){D()},K273:function(){M=!M;G()}};f.Vc=function(b,a){S.a.g();var j=S.a.hc();f.Wc(j.text,j.dc)||v();
j=f.Va(b.value);f.Kb++;S.a.ma(j);if(typeof a!="boolean"||!a)p(!1),h(n&-13)};f.Ka=function(){for(var b in f.T){var a="K"+b;if(b.charCodeAt(0)<58){var j=document.getElementsByName(a);f.T[b]=j;for(var o=0;o<j.length;o++){var d=j[o];if(d)d.onclick=C(ua[a]||f.Vc)}}}};f.ad=function(b){if(b<0)return!1;f.L=b;Math.round(24*f.L);f.Xc();S.a.ib(f.Wa);f.la();S.a.nc(b/f.gb);return!0};f.mb=function(b){if(S.a){var a=S.a.gc();return b||a<5&&(a>f.L*1.1||a<f.L)&&a>0.3?f.ad(a):!1}};f.qe=function(){return f.b&&f.b.Hb?
f.b.Hb[(n&2)==2?"l":""]:""};f.la=function(){if(f.b){var b=f.b.Rc(((n&1)==1?"s":"")+((n&12)==12?"c":"")+((n&2)==2?"l":"")),a=x(20);a&&y(a,(n&2)==2);if(a=l(16))y(a[0],(n&1)==1),y(a[1],(n&1)==1);if(a=l(273))y(a[0],(n&12)==12),y(a[1],(n&12)==12);if(b)for(var j in b)if(a=b[j],typeof a==="string"){var o=x(j.charCodeAt(0));if(o)o.value=a?a:"\u00a0"}}};var va={" ":function(){S.a.lb()},Q:function(){S.a.hb()}},Z=z(function(b){var a=b.isTrusted==e||b.isTrusted==!0;if(!E())return!0;a&&f.$c++;var j=H(b);if(ia&&
(j==91&&S.q||j==224&&S.z))j=18;j==16&&p(!1);a&&(J=!1);M=L=!1;j==17&&h(n&-5);j==18&&h(n&-9);if(j==na||n&16)return h(n&-17),!0;if(b.ctrlKey&&!b.altKey||b.modifiers&ja)return b&&(b.metaKey||b.modifiers&O)&&G(!1),!0;a&&(X=!1);j==20&&R&&S.q&&D();return!1});f.we=Z;var $=z(function(b){if(!E())return!0;var a=H(b);a==13&&(a=10);if(ia&&(a==91&&S.q||a==224&&S.z))a=18;f.Yc++;J=!0;if(a==20)return D(),!0;if(R&&a==na||n&16)return h(n|16),!0;if(b&&(b.metaKey||b.modifiers&O))return G(!0),!0;j(b,a);if(a==17||a==18||
a==16)return!0;if(R&&S.z&&(I=a,I==107))return I=0,!1;if(n&4&&(n&12)!=12&&(n&1)!=1&&a>20)return n!=4?a=!1:(a=String.fromCharCode(a),(a=va[a])?(a(),a=!0):a=!1),!a;b=b.target||b.srcElement;return o(a,b)});f.ue=$;var aa=z(function(b){if(!E())return!0;if(S.z&&!b.isTrusted)return!0;f.Zc++;if(R&&S.z){var a=b.target||b.srcElement;if(a)try{a.onfocus()}catch(d){}if(I==0){var c=String.fromCharCode(H(b));if(c in Y)return j(b,Y[c]),o(Y[c],a);else S.a.ma(c)}}if(n&16)return!0;if(n==4)return!0;if(J||!X)return J=
!1;if(E()&&I!=20&&(b=x(I)))return b.onclick(!0),!1;v();J=!1;return!0});f.ve=aa;f.ja=function(){if(w.onkeyup!=Z)w.onkeyup=Z;if(w.onkeydown!=$)w.onkeydown=$;if(w.onkeypress!=aa)w.onkeypress=aa}};S.qa=function(a,c,k){var h=document.createElement("div");h.className="kbd-button kbd-button-out";h.id=c;h.appendChild(document.createTextNode(a));if(k)h.onclick=k;h.onmouseover=function(){h.className="kbd-button kbd-button-over"};h.onmouseout=function(){h.className="kbd-button kbd-button-out"};return h};
S.Qa=function(a,c){c.className="select-dialog";a.className="trigger";a.onmouseover=function(){a.className="trigger trigger-over"};a.onmouseout=function(){a.className="trigger"};var k=this,h=S.qa("","close",function(){k.P();S.a.g()}),d=document.createElement("table"),u=document.createElement("tbody");d.cellSpacing="0";d.cellPadding="0";d.appendChild(u);d.className="select-dialog";var q=a.parentNode.clientWidth||a.parentNode.width,m=h.clientWidth||h.width;if(q&&(d.style.width=Math.max(q-5,0),m))c.style.width=
Math.max(q-m-20,0);q=document.createElement("tr");u.appendChild(q);u=document.createElement("td");q.appendChild(u);m=document.createElement("td");q.appendChild(m);u.appendChild(c);m.appendChild(h);this.Da=d;var b=c.onchange;c.onchange=function(){k.P();b&&b()};a.onclick=function(){k.Na()};this.Da.style.display="none";this.Ub=a;a.parentNode.insertBefore(this.Da,a)};S.Qa.prototype.Na=function(){this.Ub.style.display="none";this.Da.style.display=""};
S.Qa.prototype.P=function(){this.Da.style.display="none";this.Ub.style.display=""};function wa(a){return function(){return a}}S.Ob=function(a,c){return c==a?a:a.indexOf("<abbr")>=0?a:['<abbr style="border-style:none" title="',c,'">',a,"</abbr>"].join("")};
S.qb=function(a){function c(a){if(a.indexOf(":")>0){var c=a.split(/:/),a=c[0].split(/,/),D=c[1];d.cb=c[c.length>2?2:1]}else a=a.split(/,/);d.id=a[0];m=a.length>1?a[1]:d.id;b=S.Ob(d.cb,D)}function k(b){var a=d.I?"\u00c01234567890m=QWERTYUIOP\u00db\u00dd\u00dcASDFGHJKL;\u00de\u00e2ZXCVBNM\u00bc\u00be\u00bf":"\u00c01234567890m=QWERTYUIOP\u00db\u00dd\u00dcASDFGHJKL;\u00deZXCVBNM\u00bc\u00be\u00bf",c;for(c in b){var p=b[c],h=c.split(/,/);h.join(",")!=c&&h.push("");var k={};if(p){for(var l in p)if(l!=""){var m=
p[l];if(typeof m=="string")if(l.length==1)k[l.charAt(0)]=m;else for(var j=0;j<l.length;j++)k[l.charAt(j)]=m.charAt(j)}p=p[""];for(m=j=0;p&&j<p.length;){for(var o=p.indexOf("{{",j),o=o==-1?p.length:o;j<o;j++)k[a.charAt(m++)]=p.charAt(j);o<p.length&&(j=o+2,o=p.indexOf("}}",j),k[a.charAt(m++)]=p.slice(j,o));j=o+2}}for(j=0;j<h.length;j++){p=h[j];p=="-"&&(p="");p=t[p];for(m=0;m<a.length;m++)o=a.charAt(m),p[o]=k[o]?k[o]:""}}}var h=",s,l,c,sc,sl,cl,scl".split(","),d=this;d.I=!1;d.cb=a.title?a.title:a.name;
d.Ib=!1;d.fd=function(b){if(!b)return e;var a=[],c=[],d=1,h;for(h in b){var k=RegExp(h+"$"),l=b[h];a[d]=[k,l];c.push("("+h+"$)");k=RegExp(h+"|.*");k=k.exec("").length;d+=k}b=c.join("|");b=RegExp(b);return[b,a]};d.w="\u001d";d.Nb=10;var u=a.titleProvider,q=a.tooltip,m="??",b="??",t={},v=d.fd(a.transform);d.gd=RegExp("("+a.historyPruneRegex+")$");var C={};d.md=a.shortTitle;for(var l=0;l<h.length;l++)t[h[l]]={};d.Ua=function(){return u?u():b};d.bd=function(b){return function(){var a=[S.Ob("&nbsp;"+d.cb,
q)],c;for(c in b){var h=b[c];typeof h==="string"&&m!=c&&(a.length>0&&a.push("&nbsp;&nbsp;"),a.push(S.ed(h,"s2"+c,"_kbdS2('"+c+"');")))}return a.join("")}};d.Sc=function(){return d.md||d.Ua()};d.p=function(){return m};d.Rb=function(b){if(b.is102Keyboard)d.I=!0;if(b.mappings){k(b.mappings);if(b.capslock)d.Hb=b.capslock;b.view2char&&(C=b.view2char);d.Qb();d.Rb=d.Tc=wa(!0);d.Ib=!0;d.qc=function(){return b.direction=="rtl"}}};d.Rc=function(b){return t[b]};d.Va=function(b){C[b]&&(b=C[b]);return!v?b:d.kd(b)};
d.Qb=function(){d.d=[{e:"",i:-1,o:"",u:0,f:""}]};d.Qc=function(){return d.d[d.d.length-1].e};d.kd=function(b){for(var a=0;a<d.d.length;a++)d.d[a].o+=b;for(var c,a=0;a<d.d.length;a++){c=d.d[a];var h=c.e;c.i>-1&&(h=h.slice(0,c.i)+d.w+h.slice(c.i));c=d.ld(h,c.o);if(c.back>-1)break}if(a==d.d.length){for(a=0;a<d.d.length;a++)d.d[a].f+=b;c=d.d[d.d.length-1];a=c.e+b;d.Pb({e:a,i:c.i,o:"",u:0,f:""});return b}else b=d.d[a];c.back>b.u?c.back=b.f.length+c.back-b.u:(a=b.e.length-b.u,h=b.e.length-c.back,c.J=b.e.slice(a,
h)+c.J,c.back=b.f.length);for(a=0;a<d.d.length;a++)b=d.d[a],c.back>b.f.length?(b.u+=c.back-b.f.length,b.f=c.J):(h=b.f.length-c.back,b.f=b.f.slice(0,h),b.f+=c.J);a=c.bb.indexOf(d.w);b=c.bb.replace(d.w,"");d.Pb({e:b,i:a,o:"",u:0,f:""});return{back:c.back,Ia:c.J}};d.Pb=function(b){d.d.push(b);d.hd();d.jd()};d.hd=function(){for(var b=0;b<d.d.length-1;b++){var a=d.d[b];if(d.gd.exec(a.o))break}d.d.splice(0,b)};d.jd=function(){for(var b=0;b<d.d.length;b++){var a=d.d[b],c=a.o.length+a.e.length;if(!(c<d.Nb)){c=
a.e.length+a.o.length-d.Nb;a.i-=c;if(a.i<0)a.i=-1;a.e=a.e.substr(c)}}};d.ld=function(b,a){var c=b+a,h=v[0];if(h=h.exec(c)){for(var k=v[1],l=1;l<h.length&&!h[l];l++);var h=k[l][0],m=k[l][1],k=h.exec(c),l=c.slice(k.index),q=l.search(d.w)>-1?1:0,l=l.length-q-a.length,c=c.replace(h,m),h=c.slice(k.index),h=h.replace(d.w,""),c=c.replace(d.w,"")+d.w,c={back:l,J:h,bb:c}}else c={back:-1,J:a,bb:c};return c};d.Pc=function(){d.Qb()};c(a.id);a.mappings&&d.Rb(a)};var V={en:"QWERTY",fr:"AZERTY",de:"QWERTZ"};S.ed=function(a,c,k){return['<a style="text-decoration:none;cursor:pointer;font-size:80%;color:',S.a.linkColor,'" onmouseover="this.style.textDecoration=\'underline\'" onmouseout="this.style.textDecoration=\'none\'" ',c?'id="'+c+'" ':"",k?'onclick="'+k+'"':"",">",a,"</a>"].join("")};var xa="vMmh";
S.Qd=function(){function a(){var b=w.createElement("div"),a=b.style;a.visibility="hidden";b.innerHTML='<div dir="ltr" id="kbda"><div id="kbd_0"/></div>';b.setAttribute("id","kbd");b.className="outerbox";B.appendChild(b);return b}function c(){function a(){if(h==0){if(N.Fc()){var j=S.va();if(!j)return!1}S.xa?b.Dc(w.getElementsByTagName("iframe")):S.Cb<3||(b.Ta(window,"_kbdWF"),b.Lc())}h=(h+1)%10;f||(b.Mc(),b.Nc(),l.ec(),f=!0);return l.mb()}function c(){s.setTimeout(c,a()?130:1300)}w=s.document;A=w.documentElement;
B=w.body;var d=K("kbd");d&&ea(d,w);var f=!1,h=0;c();a()}function k(){var a=K("kbd_t");if(a)b.Eb(a),K("kbd_ta").onclick=function(b){if(!q()){if(S.F){var a=S.F();if(a)a.La=!1,a.ra()&&m("v")}else m("v");b&&(b.stopPropagation?b.stopPropagation():b.cancelBubble=!0)}},u();return a}function h(){var a=k();if(a&&(b.Bc||E>1))if(a.innerHTML=b.zc(),a=K("kbd_oem"),S.Db&&a&&S.a.Pa)a.innerHTML=V[l.r]}function d(){var a=K("kbd_minmax");if(!(a.childNodes.length>0)){var c;c=S.a.R?S.qa("",b.h=="v"?"max":"min",function(){b.lb()}):
S.qa("","close",function(){b.P();S.a.zb&&S.a.zb()});a.appendChild(c)}}function u(){if(S.Db&&S.a.Pa){var a=K("kbd_oem");a.title="Click to setup the physical keyboard layout.";if(a.parentNode.childNodes.length==1){var c=document.createElement("select");if(S.q){var d=document.createElement("optgroup");d.label="Native Layout";for(var f in V)d.appendChild(new Option(V[f],f));c.appendChild(d)}else for(f in V)c.options.add(new Option(V[f],f));c.selectedIndex=0;c.onchange=function(){l.pc(c.value);b.g()};
if(S.q)c.onfocus=function(){S.a.Sa=!0},c.onblur=function(){S.a.Sa=!1};new S.Qa(a,c)}}}function q(){return"vM".indexOf(b.h)>=0}function m(a){b.Oa(a);b.K()}var b=this,t,v,C,l,x={},y=1,D=1,p=1;b.S=!1;b.Sa=!1;b.uc=function(){return b.Sa};b.t=-1;var G=b.G=-1,H=-1;b.scrollX=0;b.scrollY=0;b.sb=!0;b.oe="left";b.l=0;b.s=0;b.ob="h";b.h="h";b.tc="h";b.ya={};var z=[],E=0;b.kc=1;b.ne="black";b.linkColor="blue";b.bgColor="#ebeef8";b.ie="#bbccff";b.ub="";b.tb="";b.scale=1;b.Jc=S.xa?"absolute":"fixed";b.Bc=!0;b.Bb=
!1;b.Ra=e;b.vb="";b.jc=!0;b.ic=!0;b.Gc="";b.Hc="";b.ua="";b.Pa=!0;b.R=!0;b.ta=!0;b.nb=function(a){for(var c in a){var d=c.charAt(0)=="_"?c.substring(1):c;a.hasOwnProperty(c)&&typeof b[d]!="undefined"&&(b[d]=a[c])}};b.le=function(a){b.Ra=a};b.Fb=[function(){function c(){S.Ic();d&&d()}t=a();b.Ra&&b.Ra(t);if(!l)l=b.pa=new S.j(x,b.ya,C);
b.pa.gb=b.scale;v=t.style;v.position=b.Jc;S.Ic=function(){b.yb()?b.xb():b.D()};var d=s.onresize;if(c!=d)s.onresize=c;l.fc();b.N(C,!0);b.K=function(){var a=w,c=l.oc()+"-",j;j=Math.floor(2E3*b.l)*4804+Math.floor(1200*b.s)*4+xa.indexOf(b.h);var f=[];if(j<=0)j="0";else{for(;j>0;){var d=j%62;f.push(String.fromCharCode(d+(d<10?48:d<36?55:61)));j=Math.floor(j/62)}j=f.reverse().join("")}a.cookie="KBD="+(c+j)+";expires=July 19, 2051"};if(v.position=="absolute"){S.onscroll=function(){b.scrollX=A&&A.scrollLeft;
if(!b.scrollX)b.scrollX=B.scrollLeft;b.scrollY=A&&A.scrollTop;if(!b.scrollY)b.scrollY=B.scrollTop;b.O(b.t,b.G)};var h=s.onscroll,f=function(){s.onscroll=function(){S.onscroll();h&&h()}};if(h!=s.onscroll)s.onscroll=f}}];b.Mc=function(){for(var a=0;a<b.Fb.length;a++)b.Fb[a](b)};b.gc=function(){var b=K("kbd_tx");return b?fa(b)/20:-1};b.left=function(){return t.offsetLeft};b.top=function(){return t.offsetTop};b.xc=function(){var b=S.userAgent.match(/applewebkit\/(\d+)/);if(b&&b.length==2&&parseInt(b[1],
10)>500){var b=window.innerHeight,a=document.documentElement.scrollHeight;a<b&&(b-=15);return b}b=document.documentElement||document.body;return b.clientHeight};b.yc=function(){var b=S.userAgent.match(/applewebkit\/(\d+)/);if(b&&b.length==2&&parseInt(b[1],10)>500)return window.innerWidth;b=document.documentElement||document.body;return b.clientWidth};b.n=function(){b.height=fa(t);var a=b,c;a:if(t){c=t.offsetWidth;var d=t.clip;c=c||(d?d.width:-1);if(t.currentStyle&&(d=t.currentStyle.minWidth))if(d=
d.replace("px",""),d>c){c=d;break a}}else c=-1;a.width=c;y=b.yc()-b.width;D=b.B?0:y;p=b.xc()-b.height;G=Math.floor(y*(b.B?b.l:1-b.l)+0.5);H=Math.floor(p*(1-b.s)+0.5)};b.K=function(){};b.Ta=function(b,a){if(b){var c=b.onfocus;if(c){if(c.toString().indexOf(a)<0)b.onfocus=function(){s[a](b);c()}}else b.onfocus=function(){s[a](b)}}};b.Lc=function(){var b=window.onblur;if(b){if(b.toString().indexOf("_kbdWB")<0)window.onblur=function(){s._kbdWB();b()}}else window.onblur=function(){s._kbdWB()}};b.va=function(a){for(var c=
!1,d=0;d<a.length;d++)c=b.Ec(a[d])||c;return c};b.Ec=function(a){if(!a)return!1;var c=!1,d=a.nodeName.toLowerCase(),f=a.type.toLowerCase();if(d=="textarea"||d=="input"&&(f=="text"||f=="password"))if(c=!0,!a.Ac)b.Ta(a,"_kbdSI"),a.Ac=!0;return c};b.Cc=function(a){if(a){var c=a.nodeName.toLowerCase();c=="iframe"&&b.Ta(a,"_kbdIF")}};b.Dc=function(a){for(var c=0;c<a.length;c++)b.Cc(a[c])};b.sc=ba?c:function(){};b.rb=function(a,c){c.je=a;if(!b.ya[c.p()]){E++;var d=c.p();z.push(d);b.ya[d]=c;x[a]=x[a]||[];
x[a].push(c)}return c};b.rc=function(a){E=0;z=[];b.ya={};x[a]=[];b.Ma();l=e};b.fe=function(a){for(var c in a)for(var d=c,f=a[c],h=0;h<f.length;h++)b.rb(d,new S.qb(f[h]))};b.Ja=function(b){l&&b&&l.Ja(b);C=b};b.N=function(a,c){if(l&&a)b.b=a.p(),l.N(a),b.B=a.qc(),b.n(),c||b.K()};b.k=function(a){if(b.S&&(l.k(a),m(b.h),b.c))b.c.lang=a,b.g()};b.hb=function(a,c){if(!a)a=l.ka;c||(c=1);for(var d=z[0],f=0;f<z.length;f++)z[f]==a&&(d=z[(f+z.length+c)%z.length]);b.k(d);S.a.Ab&&S.a.Ab(d)};b.g=function(){try{var a=
b.c;if(a&&a.style){var c=a.style.visibility;(!c||c=="visible")&&a.focus()}}catch(d){delete b.c}};b.kb=function(){return b.c.tagName==="TEXTAREA"};b.mc=function(){b.c&&b.kb()&&b.ma("\n")};b.Kc=function(){var a=b.c;if(window.KeyEvent){var c=document.createEvent("KeyEvents");c.initKeyEvent("keyup",!0,!0,window,!1,!1,!0,!1,16,0);a.dispatchEvent(c)}else if(document.createEvent)c=document.createEvent("UIEvents"),c.initUIEvent("keyup",!0,!0,window,1),c.keyCode=16,a.dispatchEvent(c);else if(document.createEventObject&&
a.fireEvent)c=document.createEventObject(),c.bubbles=!0,c.cancelable=!0,c.view=window,c.ctrlKey=!1,c.altKey=!1,c.shiftKey=!0,c.metaKey=!1,c.keyCode=16,a.fireEvent("onkeyup",c)};b.ma=function(a){var c=0,d=a;if(typeof a!="string")c=a.back,d=a.Ia;if((a=b.c)&&(!S.xa||a.isContentEditable)){b.g();var f=a.value||"",h=a.selectionStart;if(w.selection){h=w.selection.createRange();if(h.parentElement()==a)h.moveStart("character",-c),h.text=d;h.collapse(!1);h.select()}else if(h||h=="0"){var k=a.selectionEnd,l=
h>c?f.substring(0,h-c):"";a.value=l+d+f.substring(k,f.length);c=h+d.length-c;a.blur();a.focus();a.setSelectionRange(c,c);S.z&&S.Cb<=3&&window.KeyEvent&&(c=document.createEvent("KeyEvents"),c.initKeyEvent("keypress",!0,!0,window,!1,!1,!1,!1,0,32),a.dispatchEvent(c),c=document.createEvent("KeyEvents"),c.initKeyEvent("keypress",!0,!0,window,!1,!1,!1,!1,8,0),a.dispatchEvent(c))}else a.value=f.length<c?d:f.substring(0,f.length-c)+d;b.Bb&&b.Kc()}};b.hc=function(){var a=b.c.value,c,d=b.c,f;S.xa?(c=w.selection.createRange().getBookmark(),
f=d.createTextRange(),f.moveToBookmark(c),d=d.createTextRange(),d.collapse(!0),d.setEndPoint("EndToStart",f),c=d.text.length,f=d.text.length+f.text.length):(c=d.selectionStart,f=d.selectionEnd);c={start:c,ge:f};return{text:a,dc:c.start}};b.Eb=function(){};b.jb=function(a,c){b.Oc=q()?a:'<span style="color:#676767">'+(b.vb||c)+"</span>";h()};b.zc=function(){return b.Oc};b.Ka=function(){l.Ka()};b.pb=function(a){if(z.length==2||a&&z.length>1){var a=K("kbd-loop"),c=S.qa("","loop",function(){b.hb(e,e)});
b.ke=c;a.appendChild(c)}};b.wc=function(a){var c="";S.a.ta&&(c='');var d="";S.a.sa&&(d='<td><a  id="kbd-cfg" class="kbd-button" target="_blank" href="'+b.sa+'"/></td>');return['<center style="margin:0px auto !important;font-family:arial,sans-serif;"><table id="kbdt" border="0" style="border:0 none;" cellspacing="1px" cellpadding="0px"><tr><td style="padding: 0"><table dir=',S.a.B?"rtl":"ltr",' id="kbd_ta" width=100% cellpadding="0" cellspacing="0" border="0"><tr class="kbd-title-row">',
c,'<td id="kbd_t" align=',S.a.B?"right":"left",' style="',b.Gb?"cursor:"+b.Gb+";":"",'"></td><td align="right" id="kbd_minmax"></td><td><span id="kbd_tx" style="visibility:hidden;margin:0px;display:inline-block;padding:0px">I</span></td><td align="right" style="display:',b.h=="v"?"block":"none",'"><span id="kbd_oem" style=" font-size: xx-small;"></span></td><td id="kbd-loop"></td>',d,'</tr></table></td></tr><tr valign="top"><td align="center"><div id="kbd_mka" style="display:',
b.h=="v"?"block":"none",'"><table border="0" cellspacing="0" cellpadding="0" style="border:none;background-color:',b.bgColor,'"><tr><td align="center">',a,"</td></tr></table></div></td></tr></table></center>"].join("")};b.ib=function(a){b.pe=""+Math.floor(12*b.scale)+"px";var c=K("kbd_0");if(c)c.innerHTML=b.wc(a),d(),b.pb(!0),h(),b.Ka()};b.wb=function(){b.n();var a=b.l,c=b.s;b.l=Math.min(1,(b.B?b.t:y-b.t)/y);b.s=Math.min(1,1-b.G/p);a!=b.l&&c!=b.s&&b.K()};b.O=function(a,c){b.t=Math.min(y,Math.max(0,
a));b.G=Math.min(p,Math.max(0,c));v.right=""+((screen.width-393)/2)+"px";v.bottom=""+Math.floor(p-b.G-b.scrollY)+"px"};b.D=function(){b.n();for(var a=3;a-- >0&&(G!=b.t||H!=b.G);)b.O(G,H),b.n()};b.nc=function(){b.h!="h"&&b.D()};b.yb=function(){b.n();var a=Math.abs(D-b.t)+Math.abs(p-b.G);return a<90};b.xb=function(){b.l=b.s=0;b.n();b.O(D,p);b.D();b.wb()};b.lb=function(){if(q())b.P();else if(b.h=="M")if(S.F){var a=S.F();if(a)a.La=!0,a.ra()&&m("m")}else m("m");else b.Na()};b.oa="v";b.fb=q;b.Ma=function(){b.S=
!1};b.ja=function(){if(!b.S&&q())l.ja(),b.S=!0};b.lc=function(){return b.S};b.me=function(){};b.Oa=function(a){if(l){if("hm".indexOf(a||b.h)>=0){if(b.h=a,b.Ma(),b.g(),b.h=="h"){v.visibility="hidden";return}}else l.la();a=="M"&&!b.sb&&(a="v");b.h=a;l.na();var c=K("kbd_mka");if(c)c.style.display=a=="v"?"block":"none",b.D(),b.ja(),l.L=1,l.mb(!0),b.g(),v.visibility="visible"}};b.Nc=function(){b.Oa(b.ob)};b.C=function(){m(b.R?"m":"h")};b.P=function(){b.C();K("kbd_ta").onclick=e;b.oa=q();S.a.wa&&S.a.wa()};
b.vc=function(){if(S.F){var a=S.F();a&&a.La?m("m"):m("v")}else m("v")};b.Na=function(){m("v");b.oa=q();S.a.wa&&S.a.wa()}};S.a=new S.Qd;s._kbdHide=function(){S.a.C()};S.va=function(){var a=S.a.va(w.getElementsByTagName("textarea")),c=S.a.va(w.getElementsByTagName("input"));return a||c};S.a.od=function(a){var c=S.a.rb("-",new S.qb(a));c.Ua=c.bd({});S.a.Ja(c);S.a.nb({sb:!1,tc:"h",ub:a.ub||"\u25b2",tb:a.tb||"\u25bc",vb:void 0})};s._kbdS2=function(a){S.a.k(a)};S.a.ze=!0;S.a.ga=!1;S.a.Gb="move";S.a.Eb=function(a){var c=this;a.onmousedown=function(a){c.Dd=w.onmousemove;c.Ed=w.onmouseup;w.onmousemove=function(a){return c.Bd(a||s.event)};w.onmouseup=function(){c.ac();w.onmousemove=c.Dd;w.onmouseup=c.Ed};c.Cd(a||s.event);return!1};a.onblur=function(){c.ac()}};S.a.Ae=function(a){var c=this;c.s=Math.floor(a%1201)/1200;c.l=Math.floor(a/1201)/2E3;c.D();c.yb()&&c.xb()};S.a.ac=function(){var a=this;if(a.ga)a.wb(),a.ja(),a.ga=!1};
S.a.Cd=function(a){var c=this;c.yd=a.clientX-c.left();c.zd=a.clientY-c.top();c.ga=!0};S.a.Bd=function(a){var c=this;c.ga&&c.O(a.clientX-c.yd-c.scrollX,a.clientY-c.zd-c.scrollY);return!c.ga};N.Gd="keyboard/js/";N.aa=!0;N.Ca=!0;N.Tb=!0;N.qd=!1;N.Yd=function(a){N.aa=a};N.Be=function(a){N.Tb=a};N.Ee=function(a){N.Ca=a};N.Fc=function(){return N.Ca};N.ae=function(a){S.a.Bb=a};N.Za=function(a){if(a in N.Ha||N.Ga[a])return a==a.toUpperCase()&&(a=N.Ha[a]),a;else throw a+" is not a supported layout.";};N.db=e;N.De=function(a){N.db=a};
N.Zd=function(a){S.a.D=function(){S.a.n();var c=a(S.a.height,S.a.width);typeof c.x!=void 0&&typeof c.y!=void 0&&(S.a.O(c.x,c.y),S.a.n())}};N.Ud=function(a){a=N.Za(a);return N.Ga[a]};N.nd=function(a){typeof a=="string"&&(a=document.getElementById(a));if(a&&a.id)if(N.Ca){if(N.Sb(a))return a.id}else return a.id;return e};N.Sb=function(a){var c=a.nodeName.toLowerCase();return c=="textarea"||c=="input"&&a.type.toLowerCase()=="text"};N.$=[];N.ba={};N.Aa=[];N.Ad=function(){return S.a.c};
N.Lb=function(a){var c=N.ba[a];c?typeof c=="object"&&N.$a(c):(N.ba[a]="loading",a=N.Gd+a+".js",c=document.createElement("script"),c.src=a,document.body.appendChild(c))};N.Ba=function(a,c){for(var k=0;k<a.length;k++)if(a[k]==c)return a[k]=a[a.length-1],a.pop(),!0;return!1};
N.j=function(a,c){this.La=!1;this.b="";this.ye=a;this.V=[];this.X=[];this.cd=0;var k=[];N.U="";N.H=e;if(a)if(a.length>0&&S.a.rc("-"),typeof a[0]=="object")for(var k=a,a=[],h=0;h<k.length;h++){var d=k[h];a.push(d.id)}else if(a.length>0)for(h in a)d=N.Za(a[h]),N.Lb(d);if(!c||c.length==0)if(N.H=this,!S.a.c)S.a.c=document.activeElement;this.dd(c||e);N.Aa.push(this);for(h=0;h<k.length;h++)N.$a(k[h]);a&&a.length>0&&this.Ya(a[0])};
N.j.prototype.dd=function(a){for(var c in a){var k=N.nd(a[c]);if(k&&(this.V.push(k),N.$[k]&&N.$[k].Ba(k),N.$[k]=this,!S.a.c)){var h=document.activeElement;if(h)if(N.Ca){if(N.Sb(h)&&h.id!=k)continue}else if(h.id!=k)continue;S.a.c=document.getElementById(k)}}};N.U="";N.$a=function(a){var c=a.id;N.ba[c]=a;S.a.od(a);N.Tb&&S.a.nb({ob:"v"});N.U||S.a.sc();for(var k in N.Aa)N.Aa[k].pd(c);S.a.pb();N.db&&N.db(c);N.U=c};g=N.j.prototype;
g.rd=function(){if(N.H)return!0;var a=N.Ad();if(a)for(var c=0;c<this.V.length;c++)if(a.id==this.V[c])return!0;return!1};g.Vb=function(a){var c=N.qd||this.ra();S.a.Oa("v");S.a.k(a);this.ab(c)};g.pd=function(a){for(var c=this.X.length-1;c>=0;c--)if(this.X[c]==a){this.b=a;this.rd()&&this.Vb(a);this.X=this.X.slice(c+1);break}};g.Ba=function(a){N.Ba(this.V,a);this.V.length==0&&N.Ba(N.Aa,this)};g.Mb=function(){return N.H?S.a.b||N.U:this.b||S.a.b||N.U};
g.Ya=function(a){a=N.Za(a);a in N.ba&&typeof N.ba[a]=="object"?(this.b=a,this.Vb(a)):(this.X.push(a),N.Lb(a))};g.ra=function(){return S.a.fb()};g.Wd=function(){return!!S.a.pa};g.ee=function(a){S.a.oa=a;this.ab(a)};g.ab=function(a){a?(this.cd++,S.a.vc()):S.a.C()};N.ta=function(a){S.a.ta=a};N.ua=function(a){S.a.ua=a};N.sa=function(a){S.a.sa=a};N.ce=function(a){S.a.wa=a};N.$d=function(a){S.a.Ab=a};N.Ce=function(a){S.a.zb=a};N.Td=function(a){S.a.Pa=a};N.R=function(a){S.a.R=a};N.Vd=function(a){return i.Xd(a)};
s._kbdSI=function(a){if(a&&a!=S.a.c&&S.a.pa&&a.className!=S.a.pa.za){var c=N.H||N.$[a.id];c?(S.a.c=a,c.Ya(c.Mb()),c.ab(S.a.oa)):(S.a.c=e,N.aa?S.a.C():(S.a.Ma(),S.a.g()))}};s._kbdIF=function(){if(N.aa)S.a.c=e,S.a.C()};s._kbdWB=function(){if(N.aa&&(!S.q||!S.a.uc()))S.a.c=e,S.a.C()};s._kbdWF=function(){if(N.aa&&document.activeElement&&document.activeElement.onfocus)document.activeElement.onfocus()};S.F=function(){var a;S.a.c&&S.a.c.id&&(a=N.$[S.a.c.id]);return a?a:N.H};
google_exportSymbol("google.elements.keyboard.Keyboard",N.j);google_exportSymbol("google.elements.keyboard.Keyboard.prototype.getLayout",N.j.prototype.Mb);google_exportSymbol("google.elements.keyboard.Keyboard.prototype.setLayout",N.j.prototype.Ya);google_exportSymbol("google.elements.keyboard.Keyboard.prototype.isVisible",N.j.prototype.ra);google_exportSymbol("google.elements.keyboard.Keyboard.prototype.isReady",N.j.prototype.Wd);
google_exportSymbol("google.elements.keyboard.Keyboard.prototype.setVisible",N.j.prototype.ee);google_exportSymbol("google.elements.keyboard.setVisibilityChangeCallback",N.ce);google_exportSymbol("google.elements.keyboard.setLayoutChangeCallback",N.$d);google_exportSymbol("google.elements.keyboard.getLayoutName",N.Ud);google_exportSymbol("google.elements.keyboard.setAutoHide",N.Yd);google_exportSymbol("google.elements.keyboard.setSendShiftKeyUpEventUponInput",N.ae);
google_exportSymbol("google.elements.keyboard.enableGoogleLogo",N.ta);google_exportSymbol("google.elements.keyboard.helpLink",N.ua);google_exportSymbol("google.elements.keyboard.cfgLink",N.sa);google_exportSymbol("google.elements.keyboard.enableKeyCodeScheme",N.Td);google_exportSymbol("google.elements.keyboard.enableMinMaxMode",N.R);google_exportSymbol("google.elements.keyboard.hangulTransform",N.Vd);google_exportSymbol("google.elements.keyboard.loadme",N.$a);
google_exportSymbol("google.elements.keyboard.setHomePositionCallback",N.Zd);google_exportSymbol("google.elements.keyboard.LayoutName",N.Ga);google_exportSymbol("google.elements.keyboard.LayoutCode",N.Ha);N.Ha={ALBANIAN:"sq",ARABIC:"ar",ARMENIAN_EASTERN:"hy_east",ARMENIAN_WESTERN:"hy_west",BASQUE:"eu",BELARUSIAN:"be",BENGALI_INSCRIPT:"bn_inscript",BENGALI_PHONETIC:"bn_phone",BOSNIAN:"bs",BRAZILIAN_PORTUGUESE:"pt_br",BULGARIAN:"bg",BULGARIAN_PHONETIC:"bg_phone",CATALAN:"ca",CHEROKEE:"chr",CROATIAN:"hr",CZECH:"cs",CZECH_QWERTZ:"cs_qwertz",DANISH:"da",DARI:"prs",DUTCH:"nl",DEVANAGARI_PHONETIC:"deva_phone",ENGLISH:"en",ESTONIAN:"et",ETHIOPIC:"ethi",FINNISH:"fi",FRENCH:"fr",GALICIAN:"gl",GEORGIAN_QWERTY:"ka_qwerty",
GEORGIAN_TYPEWRITER:"ka_typewriter",GERMAN:"de",GREEK:"el",GUJARATI_INSCRIPT:"gu_inscript",GUJARATI_PHONETIC:"gu_phone",GURMUKHI_INSCRIPT:"guru_inscript",GURMUKHI_PHONETIC:"guru_phone",HEBREW:"he",HINDI:"hi",HUNGARIAN_101:"hu_101",ICELANDIC:"is",ITALIAN:"it",KANNADA_INSCRIPT:"kn_inscript",KANNADA_PHONETIC:"kn_phone",KAZAKH:"kk",KHMER:"km",KOREAN:"ko",KYRGYZ:"ky_cyrl",LAO:"lo",LATVIAN:"lv",LITHUANIAN:"lt",MACEDONIAN:"mk",MALAYALAM_INSCRIPT:"ml_inscript",MALAYALAM_PHONETIC:"ml_phone",MALTESE:"mt",MAORI:"mi",
MONGOLIAN_CYRILLIC:"mn_cyrl",MONTENEGRIN:"srp",NORWEGIAN:"no",ORIYA_INSCRIPT:"or_inscript",ORIYA_PHONETIC:"or_phone",PAN_AFRICA_LATIN:"latn_002",PASHTO:"ps",PERSIAN:"fa",POLISH:"pl",PORTUGUESE:"pt_pt",ROMANI:"rom",ROMANIAN:"ro",ROMANIAN_SR13392_PRIMARY:"ro_sr13392_primary",ROMANIAN_SR13392_SECONDARY:"ro_sr13392_secondary",RUSSIAN:"ru",SANSKRIT_PHONETIC:"sa_phone",SERBIAN_CYRILLIC:"sr_cyrl",SERBIAN_LATIN:"sr_latn",SINHALA:"si",SLOVAK:"sk",SLOVAK_QWERTY:"sk_qwerty",SLOVENIAN:"sl",SOUTHERN_UZBEK:"uzs",
SPANISH:"es_es",SWEDISH:"sv",SWISS_GERMAN:"de_ch",TAMIL_99:"ta_tamil99",TAMIL_INSCRIPT:"ta_inscript",TAMIL_PHONETIC:"ta_phone",TATAR:"tt",TELUGU_INSCRIPT:"te_inscript",TELUGU_PHONETIC:"te_phone",THAI:"th",TURKISH_F:"tr_f",TURKISH_Q:"tr_q",UIGHUR:"ug",UKRAINIAN_101:"uk_101",URDU:"ur",UZBEK_LATIN:"uz_latn",UZBEK_CYRILLIC_PHONETIC:"uz_cyrl_phone",UZBEK_CYRILLIC_TYPEWRITTER:"uz_cyrl_type",VIETNAMESE_TCVN:"vi_tcvn",VIETNAMESE_TELEX:"vi_telex",VIETNAMESE_VIQR:"vi_viqr"};
N.Ga={ar:"\u0644\u0648\u062d\u0629 \u0645\u0641\u0627\u062a\u064a\u062d \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629",be:"\u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f",bg:"\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a",bg_phone:"\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a(\u0444\u043e\u043d\u0435\u0442\u0438\u043a\u0430)",bn_inscript:"\u09ac\u09be\u0982\u09b2\u09be(INSCRIPT)",bn_phone:"\u09ac\u09be\u0982\u09b2\u09be(\u09ab\u09cb\u09a8\u09c7\u099f\u09bf\u0995)",
bs:"bosanski",ca:"catal\u00e0",chr:"\u13e3\u13b3\u13a9",cs:"\u010de\u0161tina",cs_qwertz:"\u010de\u0161tina QWERTZ",da:"dansk",de:"Deutsch",de_ch:"Deutschsprachige Schweiz",deva_phone:"\u0926\u0947\u0935\u0928\u093e\u0917\u0930\u0940(\u092b\u094b\u0928\u0947\u091f\u093f\u0915)",el:"\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac",en:"English Keyboard",es_es:"espa\u00f1ol",et:"eesti keel",ethi:"\u130d\u12d5\u12dd",eu:"Euskara",fa:"\u0641\u0627\u0631\u0633\u06cc",fi:"suomi",fr:"fran\u00e7ais",gl:"Galego",
gu_inscript:"\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0(INSCRIPT)",gu_phone:"\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0(\u0aab\u0acb\u0aa8\u0ac7\u0aa4\u0abf\u0a95)",guru_inscript:"\u0a17\u0a41\u0a30\u0a2e\u0a41\u0a16\u0a40(INSCRIPT)",guru_phone:"\u0a17\u0a41\u0a30\u0a2e\u0a41\u0a16\u0a40(\u0a2b\u0a4b\u0a28\u0a47\u0a1f\u0a3f\u0a15)",he:"\u05e2\u05b4\u05d1\u05b0\u05e8\u05b4\u05d9\u05ea",hi:"\u0939\u093f\u0902\u0926\u0940",hr:"hrvatski",hu_101:"magyar nyelv(101)",hy_east:"\u0531\u0580\u0587\u0565\u056c\u0561\u0570\u0561\u0575\u0565\u0580\u0565\u0576",
hy_west:"\u0531\u0580\u0565\u0582\u0574\u057f\u0561\u0570\u0561\u0575\u0565\u0580\u0567\u0576",is:"\u00edslenska",it:"italiano",ka_qwerty:"\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8 (\u10e5\u10ec\u10d4\u10e0\u10e2\u10e7)",ka_typewriter:"\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8 (\u10e1\u10d0\u10d1\u10d4\u10ed\u10d3\u10d8 \u10db\u10d0\u10dc\u10e5\u10d0\u10dc\u10d0)",kk:"\u049a\u0430\u0437\u0430\u049b",km:"\u17a2\u1780\u17d2\u179f\u179a\u1781\u17d2\u1798\u17c2\u179a NiDA",ko:"\ud55c\uad6d\uc5b4",kn_inscript:"\u0c95\u0ca8\u0ccd\u0ca8\u0ca1(INSCRIPT)",
kn_phone:"\u0c95\u0ca8\u0ccd\u0ca8\u0ca1(\u0cab\u0cca\u0ca8\u0cc6\u0c9f\u0cbf\u0c95\u0ccd)",ky_cyrl:"\u041a\u044b\u0440\u0433\u044b\u0437",latn_002:"Africa Latin",lo:"\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7",lt:"lietuvi\u0173 kalba",lv:"latvie\u0161u valoda",mi:"M\u0101ori",mk:"\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438",ml_inscript:"\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02(INSCRIPT)",ml_phone:"\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02(\u0d2b\u0d4a\u0d23\u0d31\u0d4d\u0d31\u0d3f\u0d15\u0d4d)",
mn_cyrl:"\u041c\u043e\u043d\u0433\u043e\u043b",mt:"Malti",nl:"Nederlands",no:"norsk",or_inscript:"\u0b13\u0b21\u0b3c\u0b3f\u0b06(INSCRIPT)",or_phone:"\u0b13\u0b21\u0b3c\u0b3f\u0b06(\u0b2b\u0b4b\u0b28\u0b47\u0b1f\u0b3f\u0b15)",pl:"polski",prs:"\u0641\u0627\u0631\u0633\u06cc \u062f\u0631\u06cc",ps:"\u067e\u069a\u062a\u0648",pt_br:"portugu\u00eas brasileiro",ro:"rom\u00e2n\u0103",ro_sr13392_primary:"rom\u00e2n\u0103 SR13392 Primary",ro_sr13392_secondary:"rom\u00e2n\u0103 SR13392 Secondary",pt_pt:"portugu\u00eas europeu",
rom:"rromani \u0107hib",ru:"\u0420\u0443\u0441\u0441\u043a\u0430\u044f \u043a\u043b\u0430\u0432\u0438\u0430\u0442\u0443\u0440\u0430",sa_phone:"\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d(\u092b\u094b\u0928\u0947\u091f\u093f\u0915)",si:"\u0dc1\u0dd4\u0daf\u0dca\u0db0 \u0dc3\u0dd2\u0d82\u0dc4\u0dbd SLS1134",sk:"slovensk\u00fd jazyk",sk_qwerty:"slovensk\u00fd jazyk - QWERTY",sl:"sloven\u0161\u010dina",sq:"shqip",srp:"Crnogorski jezik",sr_cyrl:"\u0421\u0440\u043f\u0441\u043a\u0438",sr_latn:"Srpski",
sv:"svenska",ta_tamil99:"\u0ba4\u0bae\u0bbf\u0bb4\u0bcd(TAMIL99)",ta_inscript:"\u0ba4\u0bae\u0bbf\u0bb4\u0bcd(INSCRIPT)",ta_phone:"\u0ba4\u0bae\u0bbf\u0bb4\u0bcd(\u0baa\u0bcb\u0ba9\u0bc6\u0b9f\u0bbf\u0b95\u0bcd)",te_inscript:"\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41(INSCRIPT)",te_phone:"\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41(\u0c2b\u0c4b\u0c28\u0c46\u0c1f\u0c3f\u0c15\u0c4d)",th:"\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22",tr_f:"T\u00fcrk\u00e7e - F",tr_q:"T\u00fcrk\u00e7e - Q",tt:"\u0422\u0430\u0442\u0430\u0440",
ug:"\u0626\u06c7\u064a\u063a\u06c7\u0631\u0686\u06d5",uk_101:"\u0443\u043a\u0440\u0430\u0457\u0301\u043d\u0441\u044c\u043a\u0430 \u043c\u043e\u0301\u0432\u0430(101)",ur:"\u0627\u0631\u062f\u0648",uz_latn:"O\u2018zbek",uz_cyrl_phone:"\u040e\u0437\u0431\u0435\u043a(\u0444\u043e\u043d\u0435\u0442\u0438\u0447\u043d\u0456)",uz_cyrl_type:"\u040e\u0437\u0431\u0435\u043a(\u0420\u043e\u0441\u0456\u0439\u0441\u044c\u043a\u0430)",uzs:"Southern Uzbek",vi_tcvn:"Ti\u1ebfng Vi\u1ec7t TCVN 6064",vi_telex:"Ti\u1ebfng Vi\u1ec7t Telex",
vi_viqr:"Ti\u1ebfng Vi\u1ec7t VIQR"};google_exportSymbol("google.elements.keyboard.LayoutName",N.Ga);google_exportSymbol("google.elements.keyboard.LayoutCode",N.Ha);
google.loader.loaded({"module":"elements","version":"1.0","components":["keyboard"]});
google.loader.eval.elements = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['elements']) {(function() {var scripts = google.loader.eval.scripts['elements'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.elements(scripts[i]);}})();google.loader.eval.scripts['elements'] = null;}})();